// This file will be auto-generated by Supabase CLI
// For now, we define a placeholder that matches our schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          created_at: string;
          goal: 'bulk' | 'cut' | 'maintenance';
          experience: 'novice' | 'intermediate' | 'advanced';
          preferences: Json;
          volume_landmarks: Json;
        };
        Insert: {
          id: string;
          email: string;
          created_at?: string;
          goal?: 'bulk' | 'cut' | 'maintenance';
          experience?: 'novice' | 'intermediate' | 'advanced';
          preferences?: Json;
          volume_landmarks?: Json;
        };
        Update: {
          id?: string;
          email?: string;
          created_at?: string;
          goal?: 'bulk' | 'cut' | 'maintenance';
          experience?: 'novice' | 'intermediate' | 'advanced';
          preferences?: Json;
          volume_landmarks?: Json;
        };
      };
      bodyweight_entries: {
        Row: {
          id: string;
          user_id: string;
          date: string;
          weight_kg: number;
          source: 'manual' | 'pre_workout';
        };
        Insert: {
          id?: string;
          user_id: string;
          date: string;
          weight_kg: number;
          source?: 'manual' | 'pre_workout';
        };
        Update: {
          id?: string;
          user_id?: string;
          date?: string;
          weight_kg?: number;
          source?: 'manual' | 'pre_workout';
        };
      };
      exercises: {
        Row: {
          id: string;
          name: string;
          primary_muscle: string;
          secondary_muscles: string[];
          mechanic: 'compound' | 'isolation';
          default_rep_range: number[];
          default_rir: number;
          min_weight_increment_kg: number;
          form_cues: string[];
          common_mistakes: string[];
          setup_note: string;
          movement_pattern: string;
          equipment_required: string[];
          demo_gif_url: string | null;
          demo_thumbnail_url: string | null;
          youtube_video_id: string | null;
          exercise_type: 'rep_based' | 'duration_based';
        };
        Insert: {
          id?: string;
          name: string;
          primary_muscle: string;
          secondary_muscles?: string[];
          mechanic?: 'compound' | 'isolation';
          default_rep_range?: number[];
          default_rir?: number;
          min_weight_increment_kg?: number;
          form_cues?: string[];
          common_mistakes?: string[];
          setup_note?: string;
          movement_pattern?: string;
          equipment_required?: string[];
          demo_gif_url?: string | null;
          demo_thumbnail_url?: string | null;
          youtube_video_id?: string | null;
          exercise_type?: 'rep_based' | 'duration_based';
        };
        Update: {
          id?: string;
          name?: string;
          primary_muscle?: string;
          secondary_muscles?: string[];
          mechanic?: 'compound' | 'isolation';
          default_rep_range?: number[];
          default_rir?: number;
          min_weight_increment_kg?: number;
          form_cues?: string[];
          common_mistakes?: string[];
          setup_note?: string;
          movement_pattern?: string;
          equipment_required?: string[];
          demo_gif_url?: string | null;
          demo_thumbnail_url?: string | null;
          youtube_video_id?: string | null;
          exercise_type?: 'rep_based' | 'duration_based';
        };
      };
      mesocycles: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          state: 'planned' | 'active' | 'completed';
          total_weeks: number;
          current_week: number;
          deload_week: number;
          days_per_week: number;
          split_type: string;
          fatigue_score: number;
          session_duration_minutes: number | null;
          created_at: string;
          started_at: string | null;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          state?: 'planned' | 'active' | 'completed';
          total_weeks?: number;
          current_week?: number;
          deload_week?: number;
          days_per_week?: number;
          split_type?: string;
          fatigue_score?: number;
          session_duration_minutes?: number | null;
          created_at?: string;
          started_at?: string | null;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          state?: 'planned' | 'active' | 'completed';
          total_weeks?: number;
          current_week?: number;
          deload_week?: number;
          days_per_week?: number;
          split_type?: string;
          fatigue_score?: number;
          session_duration_minutes?: number | null;
          created_at?: string;
          started_at?: string | null;
          completed_at?: string | null;
        };
      };
      workout_sessions: {
        Row: {
          id: string;
          user_id: string;
          mesocycle_id: string | null;
          state: 'planned' | 'in_progress' | 'completed' | 'skipped';
          planned_date: string;
          started_at: string | null;
          completed_at: string | null;
          pre_workout_check_in: Json | null;
          session_rpe: number | null;
          pump_rating: number | null;
          session_notes: string | null;
          completion_percent: number;
        };
        Insert: {
          id?: string;
          user_id: string;
          mesocycle_id?: string | null;
          state?: 'planned' | 'in_progress' | 'completed' | 'skipped';
          planned_date: string;
          started_at?: string | null;
          completed_at?: string | null;
          pre_workout_check_in?: Json | null;
          session_rpe?: number | null;
          pump_rating?: number | null;
          session_notes?: string | null;
          completion_percent?: number;
        };
        Update: {
          id?: string;
          user_id?: string;
          mesocycle_id?: string | null;
          state?: 'planned' | 'in_progress' | 'completed' | 'skipped';
          planned_date?: string;
          started_at?: string | null;
          completed_at?: string | null;
          pre_workout_check_in?: Json | null;
          session_rpe?: number | null;
          pump_rating?: number | null;
          session_notes?: string | null;
          completion_percent?: number;
        };
      };
      exercise_blocks: {
        Row: {
          id: string;
          workout_session_id: string;
          exercise_id: string;
          order: number;
          superset_group_id: string | null;
          superset_order: number | null;
          target_sets: number;
          target_rep_range: number[];
          target_rir: number;
          target_weight_kg: number;
          target_rest_seconds: number;
          progression_type: 'load' | 'reps' | 'sets' | 'technique' | null;
          suggestion_reason: string;
          warmup_protocol: Json;
          note: string | null;
          dropsets_per_set: number;
          drop_percentage: number;
        };
        Insert: {
          id?: string;
          workout_session_id: string;
          exercise_id: string;
          order?: number;
          superset_group_id?: string | null;
          superset_order?: number | null;
          target_sets?: number;
          target_rep_range?: number[];
          target_rir?: number;
          target_weight_kg?: number;
          target_rest_seconds?: number;
          progression_type?: 'load' | 'reps' | 'sets' | 'technique' | null;
          suggestion_reason?: string;
          warmup_protocol?: Json;
          note?: string | null;
          dropsets_per_set?: number;
          drop_percentage?: number;
        };
        Update: {
          id?: string;
          workout_session_id?: string;
          exercise_id?: string;
          order?: number;
          superset_group_id?: string | null;
          superset_order?: number | null;
          target_sets?: number;
          target_rep_range?: number[];
          target_rir?: number;
          target_weight_kg?: number;
          target_rest_seconds?: number;
          progression_type?: 'load' | 'reps' | 'sets' | 'technique' | null;
          suggestion_reason?: string;
          warmup_protocol?: Json;
          note?: string | null;
          dropsets_per_set?: number;
          drop_percentage?: number;
        };
      };
      set_logs: {
        Row: {
          id: string;
          exercise_block_id: string;
          set_number: number;
          weight_kg: number;
          reps: number;
          rpe: number;
          rest_seconds: number | null;
          is_warmup: boolean;
          set_type: 'normal' | 'warmup' | 'dropset' | 'myorep' | 'rest_pause';
          parent_set_id: string | null;
          quality: 'junk' | 'effective' | 'stimulative' | 'excessive';
          quality_reason: string;
          note: string | null;
          logged_at: string;
        };
        Insert: {
          id?: string;
          exercise_block_id: string;
          set_number: number;
          weight_kg: number;
          reps: number;
          rpe?: number;
          rest_seconds?: number | null;
          is_warmup?: boolean;
          set_type?: 'normal' | 'warmup' | 'dropset' | 'myorep' | 'rest_pause';
          parent_set_id?: string | null;
          quality?: 'junk' | 'effective' | 'stimulative' | 'excessive';
          quality_reason?: string;
          note?: string | null;
          logged_at?: string;
        };
        Update: {
          id?: string;
          exercise_block_id?: string;
          set_number?: number;
          weight_kg?: number;
          reps?: number;
          rpe?: number;
          rest_seconds?: number | null;
          is_warmup?: boolean;
          set_type?: 'normal' | 'warmup' | 'dropset' | 'myorep' | 'rest_pause';
          parent_set_id?: string | null;
          quality?: 'junk' | 'effective' | 'stimulative' | 'excessive';
          quality_reason?: string;
          note?: string | null;
          logged_at?: string;
        };
      };
      exercise_performance_snapshots: {
        Row: {
          id: string;
          user_id: string;
          exercise_id: string;
          session_date: string;
          top_set_weight_kg: number;
          top_set_reps: number;
          top_set_rpe: number;
          total_working_sets: number;
          estimated_e1rm: number;
        };
        Insert: {
          id?: string;
          user_id: string;
          exercise_id: string;
          session_date: string;
          top_set_weight_kg: number;
          top_set_reps: number;
          top_set_rpe?: number;
          total_working_sets?: number;
          estimated_e1rm?: number;
        };
        Update: {
          id?: string;
          user_id?: string;
          exercise_id?: string;
          session_date?: string;
          top_set_weight_kg?: number;
          top_set_reps?: number;
          top_set_rpe?: number;
          total_working_sets?: number;
          estimated_e1rm?: number;
        };
      };
      weekly_muscle_volume: {
        Row: {
          user_id: string;
          week_start: string;
          muscle_group: string;
          total_sets: number;
          status: 'below_mev' | 'effective' | 'optimal' | 'approaching_mrv' | 'exceeding_mrv';
        };
        Insert: {
          user_id: string;
          week_start: string;
          muscle_group: string;
          total_sets?: number;
          status?: 'below_mev' | 'effective' | 'optimal' | 'approaching_mrv' | 'exceeding_mrv';
        };
        Update: {
          user_id?: string;
          week_start?: string;
          muscle_group?: string;
          total_sets?: number;
          status?: 'below_mev' | 'effective' | 'optimal' | 'approaching_mrv' | 'exceeding_mrv';
        };
      };
      plateau_alerts: {
        Row: {
          id: string;
          user_id: string;
          exercise_id: string;
          detected_at: string;
          weeks_since_progress: number;
          suggested_actions: string[];
          dismissed: boolean;
        };
        Insert: {
          id?: string;
          user_id: string;
          exercise_id: string;
          detected_at?: string;
          weeks_since_progress?: number;
          suggested_actions?: string[];
          dismissed?: boolean;
        };
        Update: {
          id?: string;
          user_id?: string;
          exercise_id?: string;
          detected_at?: string;
          weeks_since_progress?: number;
          suggested_actions?: string[];
          dismissed?: boolean;
        };
      };
      user_profiles: {
        Row: {
          id: string;
          user_id: string;
          username: string;
          display_name: string | null;
          avatar_url: string | null;
          bio: string | null;
          profile_visibility: 'public' | 'followers_only' | 'private';
          show_workouts: boolean;
          show_stats: boolean;
          show_progress_photos: boolean;
          follower_count: number;
          following_count: number;
          workout_count: number;
          total_volume_kg: number;
          badges: Json;
          featured_achievement: string | null;
          training_experience: 'beginner' | 'intermediate' | 'advanced' | 'elite' | null;
          primary_goal: string | null;
          gym_name: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          username: string;
          display_name?: string | null;
          avatar_url?: string | null;
          bio?: string | null;
          profile_visibility?: 'public' | 'followers_only' | 'private';
          show_workouts?: boolean;
          show_stats?: boolean;
          show_progress_photos?: boolean;
          follower_count?: number;
          following_count?: number;
          workout_count?: number;
          total_volume_kg?: number;
          badges?: Json;
          featured_achievement?: string | null;
          training_experience?: 'beginner' | 'intermediate' | 'advanced' | 'elite' | null;
          primary_goal?: string | null;
          gym_name?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          username?: string;
          display_name?: string | null;
          avatar_url?: string | null;
          bio?: string | null;
          profile_visibility?: 'public' | 'followers_only' | 'private';
          show_workouts?: boolean;
          show_stats?: boolean;
          show_progress_photos?: boolean;
          follower_count?: number;
          following_count?: number;
          workout_count?: number;
          total_volume_kg?: number;
          badges?: Json;
          featured_achievement?: string | null;
          training_experience?: 'beginner' | 'intermediate' | 'advanced' | 'elite' | null;
          primary_goal?: string | null;
          gym_name?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      follows: {
        Row: {
          id: string;
          follower_id: string;
          following_id: string;
          status: 'pending' | 'accepted' | 'rejected';
          created_at: string;
          accepted_at: string | null;
        };
        Insert: {
          id?: string;
          follower_id: string;
          following_id: string;
          status?: 'pending' | 'accepted' | 'rejected';
          created_at?: string;
          accepted_at?: string | null;
        };
        Update: {
          id?: string;
          follower_id?: string;
          following_id?: string;
          status?: 'pending' | 'accepted' | 'rejected';
          created_at?: string;
          accepted_at?: string | null;
        };
      };
      activities: {
        Row: {
          id: string;
          user_id: string;
          activity_type: 'workout_completed' | 'personal_record' | 'streak_milestone' | 'badge_earned' | 'mesocycle_completed' | 'followed_user' | 'shared_workout';
          reference_type: string | null;
          reference_id: string | null;
          activity_data: Json;
          visibility: 'public' | 'followers' | 'private';
          reaction_count: number;
          comment_count: number;
          created_at: string;
          hidden_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          activity_type: 'workout_completed' | 'personal_record' | 'streak_milestone' | 'badge_earned' | 'mesocycle_completed' | 'followed_user' | 'shared_workout';
          reference_type?: string | null;
          reference_id?: string | null;
          activity_data?: Json;
          visibility?: 'public' | 'followers' | 'private';
          reaction_count?: number;
          comment_count?: number;
          created_at?: string;
          hidden_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          activity_type?: 'workout_completed' | 'personal_record' | 'streak_milestone' | 'badge_earned' | 'mesocycle_completed' | 'followed_user' | 'shared_workout';
          reference_type?: string | null;
          reference_id?: string | null;
          activity_data?: Json;
          visibility?: 'public' | 'followers' | 'private';
          reaction_count?: number;
          comment_count?: number;
          created_at?: string;
          hidden_at?: string | null;
        };
      };
      activity_reactions: {
        Row: {
          id: string;
          activity_id: string;
          user_id: string;
          reaction_type: 'like' | 'fire' | 'muscle' | 'clap';
          created_at: string;
        };
        Insert: {
          id?: string;
          activity_id: string;
          user_id: string;
          reaction_type?: 'like' | 'fire' | 'muscle' | 'clap';
          created_at?: string;
        };
        Update: {
          id?: string;
          activity_id?: string;
          user_id?: string;
          reaction_type?: 'like' | 'fire' | 'muscle' | 'clap';
          created_at?: string;
        };
      };
      activity_comments: {
        Row: {
          id: string;
          activity_id: string;
          user_id: string;
          content: string;
          parent_comment_id: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          activity_id: string;
          user_id: string;
          content: string;
          parent_comment_id?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          activity_id?: string;
          user_id?: string;
          content?: string;
          parent_comment_id?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
      };
      shared_workouts: {
        Row: {
          id: string;
          user_id: string;
          source_workout_id: string | null;
          source_mesocycle_id: string | null;
          title: string;
          description: string | null;
          workout_data: Json;
          share_type: 'single_workout' | 'program' | 'template';
          difficulty: 'beginner' | 'intermediate' | 'advanced' | null;
          duration_weeks: number | null;
          target_muscle_groups: string[] | null;
          save_count: number;
          copy_count: number;
          view_count: number;
          is_public: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          source_workout_id?: string | null;
          source_mesocycle_id?: string | null;
          title: string;
          description?: string | null;
          workout_data: Json;
          share_type: 'single_workout' | 'program' | 'template';
          difficulty?: 'beginner' | 'intermediate' | 'advanced' | null;
          duration_weeks?: number | null;
          target_muscle_groups?: string[] | null;
          save_count?: number;
          copy_count?: number;
          view_count?: number;
          is_public?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          source_workout_id?: string | null;
          source_mesocycle_id?: string | null;
          title?: string;
          description?: string | null;
          workout_data?: Json;
          share_type?: 'single_workout' | 'program' | 'template';
          difficulty?: 'beginner' | 'intermediate' | 'advanced' | null;
          duration_weeks?: number | null;
          target_muscle_groups?: string[] | null;
          save_count?: number;
          copy_count?: number;
          view_count?: number;
          is_public?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      saved_workouts: {
        Row: {
          id: string;
          user_id: string;
          shared_workout_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          shared_workout_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          shared_workout_id?: string;
          created_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      calculate_weekly_volume_leaderboard: {
        Args: Record<PropertyKey, never>;
        Returns: undefined;
      };
      calculate_weekly_workouts_leaderboard: {
        Args: Record<PropertyKey, never>;
        Returns: undefined;
      };
      calculate_monthly_volume_leaderboard: {
        Args: Record<PropertyKey, never>;
        Returns: undefined;
      };
      calculate_monthly_workouts_leaderboard: {
        Args: Record<PropertyKey, never>;
        Returns: undefined;
      };
      calculate_alltime_volume_leaderboard: {
        Args: Record<PropertyKey, never>;
        Returns: undefined;
      };
      calculate_alltime_workouts_leaderboard: {
        Args: Record<PropertyKey, never>;
        Returns: undefined;
      };
      get_leaderboard: {
        Args: {
          p_type: string;
          p_exercise_id: string | null;
          p_limit: number;
          p_offset: number;
        };
        Returns: {
          id: string;
          user_id: string;
          score: number;
          rank: number;
          previous_rank: number | null;
          period_start: string;
          period_end: string;
          rank_change: number;
          username: string;
          display_name: string | null;
          avatar_url: string | null;
        }[];
      };
      get_user_rank: {
        Args: {
          p_user_id: string;
          p_type: string;
          p_exercise_id: string | null;
        };
        Returns: {
          rank: number;
          score: number;
          previous_rank: number | null;
          rank_change: number;
          total_participants: number;
        }[];
      };
      increment_shared_workout_views: {
        Args: {
          workout_id: string;
        };
        Returns: undefined;
      };
      copy_shared_workout: {
        Args: {
          p_shared_workout_id: string;
          p_target_mesocycle_id: string | null;
        };
        Returns: string;
      };
    };
    Enums: {
      goal: 'bulk' | 'cut' | 'maintenance';
      experience: 'novice' | 'intermediate' | 'advanced';
      mechanic: 'compound' | 'isolation';
      session_state: 'planned' | 'in_progress' | 'completed' | 'skipped';
      set_quality: 'junk' | 'effective' | 'stimulative' | 'excessive';
      progression_type: 'load' | 'reps' | 'sets' | 'technique';
      volume_status: 'below_mev' | 'effective' | 'optimal' | 'approaching_mrv' | 'exceeding_mrv';
      exercise_type: 'rep_based' | 'duration_based';
      activity_type: 'workout_completed' | 'personal_record' | 'streak_milestone' | 'badge_earned' | 'mesocycle_completed' | 'followed_user' | 'shared_workout';
      reaction_type: 'like' | 'fire' | 'muscle' | 'clap';
      follow_status: 'pending' | 'accepted' | 'rejected';
      profile_visibility: 'public' | 'followers_only' | 'private';
      share_type: 'single_workout' | 'program' | 'template';
    };
  };
}
