// This file will be auto-generated by Supabase CLI
// For now, we define a placeholder that matches our schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  __InternalSupabase: {
    PostgrestVersion: '12';
  };
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          created_at: string;
          goal: 'bulk' | 'cut' | 'maintenance';
          experience: 'novice' | 'intermediate' | 'advanced';
          preferences: Json;
          volume_landmarks: Json;
          enhanced_athlete_mode: boolean;
          motion_capture_enabled: boolean;
          motion_capture_raw_retention: boolean;
        };
        Insert: {
          id: string;
          email: string;
          created_at?: string;
          goal?: 'bulk' | 'cut' | 'maintenance';
          experience?: 'novice' | 'intermediate' | 'advanced';
          preferences?: Json;
          volume_landmarks?: Json;
          enhanced_athlete_mode?: boolean;
          motion_capture_enabled?: boolean;
          motion_capture_raw_retention?: boolean;
        };
        Update: {
          id?: string;
          email?: string;
          created_at?: string;
          goal?: 'bulk' | 'cut' | 'maintenance';
          experience?: 'novice' | 'intermediate' | 'advanced';
          preferences?: Json;
          volume_landmarks?: Json;
          enhanced_athlete_mode?: boolean;
          motion_capture_enabled?: boolean;
          motion_capture_raw_retention?: boolean;
        };
        Relationships: [];
      };
      machine_calibrations: {
        Row: {
          id: string;
          user_id: string;
          exercise_id: string;
          label: string;
          seat_setting: string;
          mount_radius_mm: number;
          mount_orientation: 'top-edge' | 'bottom-edge' | 'left-edge' | 'right-edge';
          gravity_ref_start: Json;
          gravity_ref_end: Json;
          derived_pivot_axis: Json;
          axis_quality: number | null;
          derived_rom_degrees: number | null;
          schema_version: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          exercise_id: string;
          label: string;
          seat_setting?: string;
          mount_radius_mm: number;
          mount_orientation: 'top-edge' | 'bottom-edge' | 'left-edge' | 'right-edge';
          gravity_ref_start: Json;
          gravity_ref_end: Json;
          derived_pivot_axis: Json;
          axis_quality?: number | null;
          derived_rom_degrees?: number | null;
          schema_version?: number;
          created_at?: string;
        };
        Update: {
          label?: string;
          seat_setting?: string;
          mount_radius_mm?: number;
          mount_orientation?: 'top-edge' | 'bottom-edge' | 'left-edge' | 'right-edge';
          derived_rom_degrees?: number | null;
        };
        Relationships: [];
      };
      motion_captures: {
        Row: {
          id: string;
          user_id: string;
          set_id: string;
          calibration_id: string;
          side: 'left' | 'right';
          started_at: string;
          duration_ms: number;
          sample_rate_hz_mean: number;
          sample_rate_hz_stddev: number;
          dropped_sample_count: number;
          clip_detected: boolean;
          reps: Json;
          quality_flags: string[];
          provenance: string;
          schema_version: number;
          created_at: string;
        };
        Insert: {
          id: string;
          user_id: string;
          set_id: string;
          calibration_id: string;
          side: 'left' | 'right';
          started_at: string;
          duration_ms: number;
          sample_rate_hz_mean: number;
          sample_rate_hz_stddev: number;
          dropped_sample_count?: number;
          clip_detected?: boolean;
          reps: Json;
          quality_flags?: string[];
          provenance?: string;
          schema_version?: number;
          created_at?: string;
        };
        Update: {
          quality_flags?: string[];
        };
        Relationships: [];
      };
      motion_capture_raw_buffers: {
        Row: {
          capture_id: string;
          user_id: string;
          workout_session_id: string;
          sample_count: number;
          samples: Json;
          created_at: string;
        };
        Insert: {
          capture_id: string;
          user_id: string;
          workout_session_id: string;
          sample_count: number;
          samples: Json;
          created_at?: string;
        };
        Update: Record<string, never>;
        Relationships: [];
      };
      bodyweight_entries: {
        Row: {
          id: string;
          user_id: string;
          date: string;
          weight_kg: number;
          source: 'manual' | 'pre_workout';
        };
        Insert: {
          id?: string;
          user_id: string;
          date: string;
          weight_kg: number;
          source?: 'manual' | 'pre_workout';
        };
        Update: {
          id?: string;
          user_id?: string;
          date?: string;
          weight_kg?: number;
          source?: 'manual' | 'pre_workout';
        };
        Relationships: [];
      };
      exercises: {
        Row: {
          id: string;
          name: string;
          primary_muscle: string;
          secondary_muscles: string[];
          mechanic: 'compound' | 'isolation';
          default_rep_range: number[];
          default_rir: number;
          min_weight_increment_kg: number;
          available_increments_kg: number[] | null;
          progression_model: 'e1rm' | 'rep_total' | null;
          rep_boundary: 'crisp' | 'drifting';
          form_cues: string[];
          common_mistakes: string[];
          setup_note: string;
          movement_pattern: string;
          rom_demands: string[];
          equipment_required: string[];
          equipment_class: string | null;
          demo_gif_url: string | null;
          demo_thumbnail_url: string | null;
          youtube_video_id: string | null;
          exercise_type: 'rep_based' | 'duration_based';
        };
        Insert: {
          id?: string;
          name: string;
          primary_muscle: string;
          secondary_muscles?: string[];
          mechanic?: 'compound' | 'isolation';
          default_rep_range?: number[];
          default_rir?: number;
          min_weight_increment_kg?: number;
          available_increments_kg?: number[] | null;
          progression_model?: 'e1rm' | 'rep_total' | null;
          rep_boundary?: 'crisp' | 'drifting';
          form_cues?: string[];
          common_mistakes?: string[];
          setup_note?: string;
          movement_pattern?: string;
          rom_demands?: string[];
          equipment_required?: string[];
          equipment_class?: string | null;
          demo_gif_url?: string | null;
          demo_thumbnail_url?: string | null;
          youtube_video_id?: string | null;
          exercise_type?: 'rep_based' | 'duration_based';
        };
        Update: {
          id?: string;
          name?: string;
          primary_muscle?: string;
          secondary_muscles?: string[];
          mechanic?: 'compound' | 'isolation';
          default_rep_range?: number[];
          default_rir?: number;
          min_weight_increment_kg?: number;
          available_increments_kg?: number[] | null;
          progression_model?: 'e1rm' | 'rep_total' | null;
          rep_boundary?: 'crisp' | 'drifting';
          form_cues?: string[];
          common_mistakes?: string[];
          setup_note?: string;
          movement_pattern?: string;
          rom_demands?: string[];
          equipment_required?: string[];
          equipment_class?: string | null;
          demo_gif_url?: string | null;
          demo_thumbnail_url?: string | null;
          youtube_video_id?: string | null;
          exercise_type?: 'rep_based' | 'duration_based';
        };
        Relationships: [];
      };
      mesocycles: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          state: 'planned' | 'active' | 'completed';
          total_weeks: number;
          current_week: number;
          deload_week: number;
          days_per_week: number;
          split_type: string;
          fatigue_score: number;
          session_duration_minutes: number | null;
          deload_recommended_at: string | null;
          deload_reasons: Json | null;
          generated_with_enhanced_mode: boolean | null;
          created_at: string;
          started_at: string | null;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          state?: 'planned' | 'active' | 'completed';
          total_weeks?: number;
          current_week?: number;
          deload_week?: number;
          days_per_week?: number;
          split_type?: string;
          fatigue_score?: number;
          session_duration_minutes?: number | null;
          deload_recommended_at?: string | null;
          deload_reasons?: Json | null;
          generated_with_enhanced_mode?: boolean | null;
          created_at?: string;
          started_at?: string | null;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          state?: 'planned' | 'active' | 'completed';
          total_weeks?: number;
          current_week?: number;
          deload_week?: number;
          days_per_week?: number;
          split_type?: string;
          fatigue_score?: number;
          session_duration_minutes?: number | null;
          deload_recommended_at?: string | null;
          deload_reasons?: Json | null;
          generated_with_enhanced_mode?: boolean | null;
          created_at?: string;
          started_at?: string | null;
          completed_at?: string | null;
        };
        Relationships: [];
      };
      workout_sessions: {
        Row: {
          id: string;
          user_id: string;
          mesocycle_id: string | null;
          state: 'planned' | 'in_progress' | 'completed' | 'skipped' | 'auto_discarded';
          planned_date: string;
          started_at: string | null;
          completed_at: string | null;
          pre_workout_check_in: Json | null;
          session_rpe: number | null;
          pump_rating: number | null;
          session_notes: string | null;
          completion_percent: number;
          duration_seconds: number | null;
          auto_discarded_at: string | null;
          origin: 'scheduled' | 'empty' | 'ai_suggested' | 'repeat' | null;
          is_deload: boolean;
        };
        Insert: {
          id?: string;
          user_id: string;
          mesocycle_id?: string | null;
          state?: 'planned' | 'in_progress' | 'completed' | 'skipped' | 'auto_discarded';
          planned_date: string;
          started_at?: string | null;
          completed_at?: string | null;
          pre_workout_check_in?: Json | null;
          session_rpe?: number | null;
          pump_rating?: number | null;
          session_notes?: string | null;
          completion_percent?: number;
          duration_seconds?: number | null;
          auto_discarded_at?: string | null;
          origin?: 'scheduled' | 'empty' | 'ai_suggested' | 'repeat' | null;
          is_deload?: boolean;
        };
        Update: {
          id?: string;
          user_id?: string;
          mesocycle_id?: string | null;
          state?: 'planned' | 'in_progress' | 'completed' | 'skipped' | 'auto_discarded';
          planned_date?: string;
          started_at?: string | null;
          completed_at?: string | null;
          pre_workout_check_in?: Json | null;
          session_rpe?: number | null;
          pump_rating?: number | null;
          session_notes?: string | null;
          completion_percent?: number;
          duration_seconds?: number | null;
          auto_discarded_at?: string | null;
          origin?: 'scheduled' | 'empty' | 'ai_suggested' | 'repeat' | null;
          is_deload?: boolean;
        };
        Relationships: [];
      };
      saved_meals: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          items: Json;
          total_calories: number;
          total_protein: number;
          total_carbs: number;
          total_fat: number;
          times_logged: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          items?: Json;
          total_calories?: number;
          total_protein?: number;
          total_carbs?: number;
          total_fat?: number;
          times_logged?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          items?: Json;
          total_calories?: number;
          total_protein?: number;
          total_carbs?: number;
          total_fat?: number;
          times_logged?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      session_muscle_feedback: {
        Row: {
          id: string;
          user_id: string;
          session_id: string;
          muscle_group: string;
          soreness_before: number | null;
          pump: number | null;
          workload: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          session_id: string;
          muscle_group: string;
          soreness_before?: number | null;
          pump?: number | null;
          workload?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          session_id?: string;
          muscle_group?: string;
          soreness_before?: number | null;
          pump?: number | null;
          workload?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      exercise_blocks: {
        Row: {
          id: string;
          workout_session_id: string;
          exercise_id: string;
          order: number;
          superset_group_id: string | null;
          superset_order: number | null;
          target_sets: number;
          target_rep_range: number[];
          target_rir: number;
          target_weight_kg: number;
          target_rest_seconds: number;
          progression_type: 'load' | 'reps' | 'sets' | 'technique' | null;
          suggestion_reason: string;
          warmup_protocol: Json;
          note: string | null;
          dropsets_per_set: number;
          drop_percentage: number;
          skipped_at: string | null;
          pump: number | null;
          workload: number | null;
          equipment_changed: boolean;
        };
        Insert: {
          id?: string;
          workout_session_id: string;
          exercise_id: string;
          order?: number;
          superset_group_id?: string | null;
          superset_order?: number | null;
          target_sets?: number;
          target_rep_range?: number[];
          target_rir?: number;
          target_weight_kg?: number;
          target_rest_seconds?: number;
          progression_type?: 'load' | 'reps' | 'sets' | 'technique' | null;
          suggestion_reason?: string;
          warmup_protocol?: Json;
          note?: string | null;
          dropsets_per_set?: number;
          drop_percentage?: number;
          skipped_at?: string | null;
          pump?: number | null;
          workload?: number | null;
          equipment_changed?: boolean;
        };
        Update: {
          id?: string;
          workout_session_id?: string;
          exercise_id?: string;
          order?: number;
          superset_group_id?: string | null;
          superset_order?: number | null;
          target_sets?: number;
          target_rep_range?: number[];
          target_rir?: number;
          target_weight_kg?: number;
          target_rest_seconds?: number;
          progression_type?: 'load' | 'reps' | 'sets' | 'technique' | null;
          suggestion_reason?: string;
          warmup_protocol?: Json;
          note?: string | null;
          dropsets_per_set?: number;
          drop_percentage?: number;
          skipped_at?: string | null;
          pump?: number | null;
          workload?: number | null;
          equipment_changed?: boolean;
        };
        Relationships: [];
      };
      joint_pain_events: {
        Row: {
          id: string;
          user_id: string;
          session_id: string;
          exercise_id: string | null;
          set_log_id: string | null;
          joint: string;
          severity: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          session_id: string;
          exercise_id?: string | null;
          set_log_id?: string | null;
          joint: string;
          severity: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          session_id?: string;
          exercise_id?: string | null;
          set_log_id?: string | null;
          joint?: string;
          severity?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      sleep_log: {
        Row: {
          id: string;
          user_id: string;
          local_day: string;
          hours: number;
          quality: string;
          source: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          local_day: string;
          hours: number;
          quality: string;
          source?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          local_day?: string;
          hours?: number;
          quality?: string;
          source?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      user_muscle_recovery_multipliers: {
        Row: {
          id: string;
          user_id: string;
          muscle_group: string;
          recovery_multiplier: number;
          updated_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          muscle_group: string;
          recovery_multiplier?: number;
          updated_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          muscle_group?: string;
          recovery_multiplier?: number;
          updated_at?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      set_logs: {
        Row: {
          id: string;
          exercise_block_id: string;
          set_number: number;
          weight_kg: number;
          reps: number;
          rpe: number;
          rest_seconds: number | null;
          is_warmup: boolean;
          set_type: 'normal' | 'warmup' | 'dropset' | 'myorep' | 'rest_pause';
          parent_set_id: string | null;
          quality: 'junk' | 'effective' | 'stimulative' | 'excessive';
          quality_reason: string;
          note: string | null;
          logged_at: string;
          set_role: 'working' | 'ramp' | null;
          suggestion_engine_version: number | null;
        };
        Insert: {
          id?: string;
          exercise_block_id: string;
          set_number: number;
          weight_kg: number;
          reps: number;
          rpe?: number;
          rest_seconds?: number | null;
          is_warmup?: boolean;
          set_type?: 'normal' | 'warmup' | 'dropset' | 'myorep' | 'rest_pause';
          parent_set_id?: string | null;
          quality?: 'junk' | 'effective' | 'stimulative' | 'excessive';
          quality_reason?: string;
          note?: string | null;
          logged_at?: string;
          set_role?: 'working' | 'ramp' | null;
          suggestion_engine_version?: number | null;
        };
        Update: {
          id?: string;
          exercise_block_id?: string;
          set_number?: number;
          weight_kg?: number;
          reps?: number;
          rpe?: number;
          rest_seconds?: number | null;
          is_warmup?: boolean;
          set_type?: 'normal' | 'warmup' | 'dropset' | 'myorep' | 'rest_pause';
          parent_set_id?: string | null;
          quality?: 'junk' | 'effective' | 'stimulative' | 'excessive';
          quality_reason?: string;
          note?: string | null;
          logged_at?: string;
          set_role?: 'working' | 'ramp' | null;
          suggestion_engine_version?: number | null;
        };
        Relationships: [];
      };
      exercise_performance_snapshots: {
        Row: {
          id: string;
          user_id: string;
          exercise_id: string;
          session_date: string;
          top_set_weight_kg: number;
          top_set_reps: number;
          top_set_rpe: number;
          total_working_sets: number;
          estimated_e1rm: number | null;
          estimated_e1rm_legacy: number | null;
          e1rm_version: number;
          is_deload: boolean;
        };
        Insert: {
          id?: string;
          user_id: string;
          exercise_id: string;
          session_date: string;
          top_set_weight_kg: number;
          top_set_reps: number;
          top_set_rpe?: number;
          total_working_sets?: number;
          estimated_e1rm?: number | null;
          estimated_e1rm_legacy?: number | null;
          e1rm_version?: number;
          is_deload?: boolean;
        };
        Update: {
          id?: string;
          user_id?: string;
          exercise_id?: string;
          session_date?: string;
          top_set_weight_kg?: number;
          top_set_reps?: number;
          top_set_rpe?: number;
          total_working_sets?: number;
          estimated_e1rm?: number | null;
          estimated_e1rm_legacy?: number | null;
          e1rm_version?: number;
          is_deload?: boolean;
        };
        Relationships: [];
      };
      plateau_alerts: {
        Row: {
          id: string;
          user_id: string;
          exercise_id: string;
          detected_at: string;
          weeks_since_progress: number;
          suggested_actions: string[];
          dismissed: boolean;
        };
        Insert: {
          id?: string;
          user_id: string;
          exercise_id: string;
          detected_at?: string;
          weeks_since_progress?: number;
          suggested_actions?: string[];
          dismissed?: boolean;
        };
        Update: {
          id?: string;
          user_id?: string;
          exercise_id?: string;
          detected_at?: string;
          weeks_since_progress?: number;
          suggested_actions?: string[];
          dismissed?: boolean;
        };
        Relationships: [];
      };
      ai_coaching_conversations: {
        Row: {
          id: string;
          user_id: string;
          title: string | null;
          started_at: string;
          last_message_at: string;
          messages: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title?: string | null;
          started_at?: string;
          last_message_at?: string;
          messages?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string | null;
          started_at?: string;
          last_message_at?: string;
          messages?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      ai_exercise_completions: {
        Row: {
          id: string;
          user_id: string;
          exercise_name: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          exercise_name: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          exercise_name?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      user_profiles: {
        Row: {
          id: string;
          user_id: string;
          username: string;
          display_name: string | null;
          avatar_url: string | null;
          bio: string | null;
          profile_visibility: 'public' | 'followers_only' | 'private';
          show_workouts: boolean;
          show_stats: boolean;
          show_progress_photos: boolean;
          follower_count: number;
          following_count: number;
          workout_count: number;
          total_volume_kg: number;
          badges: Json;
          featured_achievement: string | null;
          training_experience: 'beginner' | 'intermediate' | 'advanced' | 'elite' | null;
          primary_goal: string | null;
          gym_name: string | null;
          show_on_leaderboards: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          username: string;
          display_name?: string | null;
          avatar_url?: string | null;
          bio?: string | null;
          profile_visibility?: 'public' | 'followers_only' | 'private';
          show_workouts?: boolean;
          show_stats?: boolean;
          show_progress_photos?: boolean;
          follower_count?: number;
          following_count?: number;
          workout_count?: number;
          total_volume_kg?: number;
          badges?: Json;
          featured_achievement?: string | null;
          training_experience?: 'beginner' | 'intermediate' | 'advanced' | 'elite' | null;
          primary_goal?: string | null;
          gym_name?: string | null;
          show_on_leaderboards?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          username?: string;
          display_name?: string | null;
          avatar_url?: string | null;
          bio?: string | null;
          profile_visibility?: 'public' | 'followers_only' | 'private';
          show_workouts?: boolean;
          show_stats?: boolean;
          show_progress_photos?: boolean;
          follower_count?: number;
          following_count?: number;
          workout_count?: number;
          total_volume_kg?: number;
          badges?: Json;
          featured_achievement?: string | null;
          training_experience?: 'beginner' | 'intermediate' | 'advanced' | 'elite' | null;
          primary_goal?: string | null;
          gym_name?: string | null;
          show_on_leaderboards?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      goal: 'bulk' | 'cut' | 'maintenance';
      experience: 'novice' | 'intermediate' | 'advanced';
      mechanic: 'compound' | 'isolation';
      session_state: 'planned' | 'in_progress' | 'completed' | 'skipped' | 'auto_discarded';
      set_quality: 'junk' | 'effective' | 'stimulative' | 'excessive';
      progression_type: 'load' | 'reps' | 'sets' | 'technique';
      volume_status: 'below_mev' | 'effective' | 'optimal' | 'approaching_mrv' | 'exceeding_mrv';
      exercise_type: 'rep_based' | 'duration_based';
    };
  };
}

