// This file will be auto-generated by Supabase CLI
// For now, we define a placeholder that matches our schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          created_at: string;
          goal: 'bulk' | 'cut' | 'maintenance';
          experience: 'novice' | 'intermediate' | 'advanced';
          preferences: Json;
          volume_landmarks: Json;
        };
        Insert: {
          id: string;
          email: string;
          created_at?: string;
          goal?: 'bulk' | 'cut' | 'maintenance';
          experience?: 'novice' | 'intermediate' | 'advanced';
          preferences?: Json;
          volume_landmarks?: Json;
        };
        Update: {
          id?: string;
          email?: string;
          created_at?: string;
          goal?: 'bulk' | 'cut' | 'maintenance';
          experience?: 'novice' | 'intermediate' | 'advanced';
          preferences?: Json;
          volume_landmarks?: Json;
        };
      };
      bodyweight_entries: {
        Row: {
          id: string;
          user_id: string;
          date: string;
          weight_kg: number;
          source: 'manual' | 'pre_workout';
        };
        Insert: {
          id?: string;
          user_id: string;
          date: string;
          weight_kg: number;
          source?: 'manual' | 'pre_workout';
        };
        Update: {
          id?: string;
          user_id?: string;
          date?: string;
          weight_kg?: number;
          source?: 'manual' | 'pre_workout';
        };
      };
      exercises: {
        Row: {
          id: string;
          name: string;
          primary_muscle: string;
          secondary_muscles: string[];
          mechanic: 'compound' | 'isolation';
          default_rep_range: number[];
          default_rir: number;
          min_weight_increment_kg: number;
          form_cues: string[];
          common_mistakes: string[];
          setup_note: string;
          movement_pattern: string;
          equipment_required: string[];
        };
        Insert: {
          id?: string;
          name: string;
          primary_muscle: string;
          secondary_muscles?: string[];
          mechanic?: 'compound' | 'isolation';
          default_rep_range?: number[];
          default_rir?: number;
          min_weight_increment_kg?: number;
          form_cues?: string[];
          common_mistakes?: string[];
          setup_note?: string;
          movement_pattern?: string;
          equipment_required?: string[];
        };
        Update: {
          id?: string;
          name?: string;
          primary_muscle?: string;
          secondary_muscles?: string[];
          mechanic?: 'compound' | 'isolation';
          default_rep_range?: number[];
          default_rir?: number;
          min_weight_increment_kg?: number;
          form_cues?: string[];
          common_mistakes?: string[];
          setup_note?: string;
          movement_pattern?: string;
          equipment_required?: string[];
        };
      };
      mesocycles: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          state: 'planned' | 'active' | 'completed';
          total_weeks: number;
          current_week: number;
          deload_week: number;
          days_per_week: number;
          split_type: string;
          fatigue_score: number;
          created_at: string;
          started_at: string | null;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          state?: 'planned' | 'active' | 'completed';
          total_weeks?: number;
          current_week?: number;
          deload_week?: number;
          days_per_week?: number;
          split_type?: string;
          fatigue_score?: number;
          created_at?: string;
          started_at?: string | null;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          state?: 'planned' | 'active' | 'completed';
          total_weeks?: number;
          current_week?: number;
          deload_week?: number;
          days_per_week?: number;
          split_type?: string;
          fatigue_score?: number;
          created_at?: string;
          started_at?: string | null;
          completed_at?: string | null;
        };
      };
      workout_sessions: {
        Row: {
          id: string;
          user_id: string;
          mesocycle_id: string | null;
          state: 'planned' | 'in_progress' | 'completed' | 'skipped';
          planned_date: string;
          started_at: string | null;
          completed_at: string | null;
          pre_workout_check_in: Json | null;
          session_rpe: number | null;
          pump_rating: number | null;
          session_notes: string | null;
          completion_percent: number;
        };
        Insert: {
          id?: string;
          user_id: string;
          mesocycle_id?: string | null;
          state?: 'planned' | 'in_progress' | 'completed' | 'skipped';
          planned_date: string;
          started_at?: string | null;
          completed_at?: string | null;
          pre_workout_check_in?: Json | null;
          session_rpe?: number | null;
          pump_rating?: number | null;
          session_notes?: string | null;
          completion_percent?: number;
        };
        Update: {
          id?: string;
          user_id?: string;
          mesocycle_id?: string | null;
          state?: 'planned' | 'in_progress' | 'completed' | 'skipped';
          planned_date?: string;
          started_at?: string | null;
          completed_at?: string | null;
          pre_workout_check_in?: Json | null;
          session_rpe?: number | null;
          pump_rating?: number | null;
          session_notes?: string | null;
          completion_percent?: number;
        };
      };
      exercise_blocks: {
        Row: {
          id: string;
          workout_session_id: string;
          exercise_id: string;
          order: number;
          superset_group_id: string | null;
          superset_order: number | null;
          target_sets: number;
          target_rep_range: number[];
          target_rir: number;
          target_weight_kg: number;
          target_rest_seconds: number;
          progression_type: 'load' | 'reps' | 'sets' | 'technique' | null;
          suggestion_reason: string;
          warmup_protocol: Json;
          note: string | null;
          dropsets_per_set: number;
          drop_percentage: number;
        };
        Insert: {
          id?: string;
          workout_session_id: string;
          exercise_id: string;
          order?: number;
          superset_group_id?: string | null;
          superset_order?: number | null;
          target_sets?: number;
          target_rep_range?: number[];
          target_rir?: number;
          target_weight_kg?: number;
          target_rest_seconds?: number;
          progression_type?: 'load' | 'reps' | 'sets' | 'technique' | null;
          suggestion_reason?: string;
          warmup_protocol?: Json;
          note?: string | null;
          dropsets_per_set?: number;
          drop_percentage?: number;
        };
        Update: {
          id?: string;
          workout_session_id?: string;
          exercise_id?: string;
          order?: number;
          superset_group_id?: string | null;
          superset_order?: number | null;
          target_sets?: number;
          target_rep_range?: number[];
          target_rir?: number;
          target_weight_kg?: number;
          target_rest_seconds?: number;
          progression_type?: 'load' | 'reps' | 'sets' | 'technique' | null;
          suggestion_reason?: string;
          warmup_protocol?: Json;
          note?: string | null;
          dropsets_per_set?: number;
          drop_percentage?: number;
        };
      };
      set_logs: {
        Row: {
          id: string;
          exercise_block_id: string;
          set_number: number;
          weight_kg: number;
          reps: number;
          rpe: number;
          rest_seconds: number | null;
          is_warmup: boolean;
          set_type: 'normal' | 'warmup' | 'dropset' | 'myorep' | 'rest_pause';
          parent_set_id: string | null;
          quality: 'junk' | 'effective' | 'stimulative' | 'excessive';
          quality_reason: string;
          note: string | null;
          logged_at: string;
        };
        Insert: {
          id?: string;
          exercise_block_id: string;
          set_number: number;
          weight_kg: number;
          reps: number;
          rpe?: number;
          rest_seconds?: number | null;
          is_warmup?: boolean;
          set_type?: 'normal' | 'warmup' | 'dropset' | 'myorep' | 'rest_pause';
          parent_set_id?: string | null;
          quality?: 'junk' | 'effective' | 'stimulative' | 'excessive';
          quality_reason?: string;
          note?: string | null;
          logged_at?: string;
        };
        Update: {
          id?: string;
          exercise_block_id?: string;
          set_number?: number;
          weight_kg?: number;
          reps?: number;
          rpe?: number;
          rest_seconds?: number | null;
          is_warmup?: boolean;
          set_type?: 'normal' | 'warmup' | 'dropset' | 'myorep' | 'rest_pause';
          parent_set_id?: string | null;
          quality?: 'junk' | 'effective' | 'stimulative' | 'excessive';
          quality_reason?: string;
          note?: string | null;
          logged_at?: string;
        };
      };
      exercise_performance_snapshots: {
        Row: {
          id: string;
          user_id: string;
          exercise_id: string;
          session_date: string;
          top_set_weight_kg: number;
          top_set_reps: number;
          top_set_rpe: number;
          total_working_sets: number;
          estimated_e1rm: number;
        };
        Insert: {
          id?: string;
          user_id: string;
          exercise_id: string;
          session_date: string;
          top_set_weight_kg: number;
          top_set_reps: number;
          top_set_rpe?: number;
          total_working_sets?: number;
          estimated_e1rm?: number;
        };
        Update: {
          id?: string;
          user_id?: string;
          exercise_id?: string;
          session_date?: string;
          top_set_weight_kg?: number;
          top_set_reps?: number;
          top_set_rpe?: number;
          total_working_sets?: number;
          estimated_e1rm?: number;
        };
      };
      weekly_muscle_volume: {
        Row: {
          user_id: string;
          week_start: string;
          muscle_group: string;
          total_sets: number;
          status: 'below_mev' | 'effective' | 'optimal' | 'approaching_mrv' | 'exceeding_mrv';
        };
        Insert: {
          user_id: string;
          week_start: string;
          muscle_group: string;
          total_sets?: number;
          status?: 'below_mev' | 'effective' | 'optimal' | 'approaching_mrv' | 'exceeding_mrv';
        };
        Update: {
          user_id?: string;
          week_start?: string;
          muscle_group?: string;
          total_sets?: number;
          status?: 'below_mev' | 'effective' | 'optimal' | 'approaching_mrv' | 'exceeding_mrv';
        };
      };
      plateau_alerts: {
        Row: {
          id: string;
          user_id: string;
          exercise_id: string;
          detected_at: string;
          weeks_since_progress: number;
          suggested_actions: string[];
          dismissed: boolean;
        };
        Insert: {
          id?: string;
          user_id: string;
          exercise_id: string;
          detected_at?: string;
          weeks_since_progress?: number;
          suggested_actions?: string[];
          dismissed?: boolean;
        };
        Update: {
          id?: string;
          user_id?: string;
          exercise_id?: string;
          detected_at?: string;
          weeks_since_progress?: number;
          suggested_actions?: string[];
          dismissed?: boolean;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      goal: 'bulk' | 'cut' | 'maintenance';
      experience: 'novice' | 'intermediate' | 'advanced';
      mechanic: 'compound' | 'isolation';
      session_state: 'planned' | 'in_progress' | 'completed' | 'skipped';
      set_quality: 'junk' | 'effective' | 'stimulative' | 'excessive';
      progression_type: 'load' | 'reps' | 'sets' | 'technique';
      volume_status: 'below_mev' | 'effective' | 'optimal' | 'approaching_mrv' | 'exceeding_mrv';
    };
  };
}

