-- SQL to update database with MuscleWiki videos
-- Run this in Supabase SQL Editor after downloading videos
-- Note: These are MP4 video files - update frontend to use <video> tags

UPDATE exercises SET demo_gif_url = '/exercise-demos/barbell-bench-press.mp4' WHERE name = 'Barbell Bench Press';
UPDATE exercises SET demo_gif_url = '/exercise-demos/dumbbell-bench-press.mp4' WHERE name = 'Dumbbell Bench Press';
UPDATE exercises SET demo_gif_url = '/exercise-demos/incline-dumbbell-press.mp4' WHERE name = 'Incline Dumbbell Press';
UPDATE exercises SET demo_gif_url = '/exercise-demos/cable-fly.mp4' WHERE name = 'Cable Fly';
UPDATE exercises SET demo_gif_url = '/exercise-demos/dips--chest-focus-.mp4' WHERE name = 'Dips (Chest Focus)';
UPDATE exercises SET demo_gif_url = '/exercise-demos/machine-chest-press.mp4' WHERE name = 'Machine Chest Press';
UPDATE exercises SET demo_gif_url = '/exercise-demos/barbell-row.mp4' WHERE name = 'Barbell Row';
UPDATE exercises SET demo_gif_url = '/exercise-demos/dumbbell-row.mp4' WHERE name = 'Dumbbell Row';
UPDATE exercises SET demo_gif_url = '/exercise-demos/lat-pulldown.mp4' WHERE name = 'Lat Pulldown';
UPDATE exercises SET demo_gif_url = '/exercise-demos/pull-ups.mp4' WHERE name = 'Pull-Ups';
UPDATE exercises SET demo_gif_url = '/exercise-demos/cable-row.mp4' WHERE name = 'Cable Row';
UPDATE exercises SET demo_gif_url = '/exercise-demos/deadlift.mp4' WHERE name = 'Deadlift';
UPDATE exercises SET demo_gif_url = '/exercise-demos/chest-supported-row.mp4' WHERE name = 'Chest Supported Row';
UPDATE exercises SET demo_gif_url = '/exercise-demos/overhead-press.mp4' WHERE name = 'Overhead Press';
UPDATE exercises SET demo_gif_url = '/exercise-demos/lateral-raise.mp4' WHERE name = 'Lateral Raise';
UPDATE exercises SET demo_gif_url = '/exercise-demos/rear-delt-fly.mp4' WHERE name = 'Rear Delt Fly';
UPDATE exercises SET demo_gif_url = '/exercise-demos/dumbbell-shoulder-press.mp4' WHERE name = 'Dumbbell Shoulder Press';
UPDATE exercises SET demo_gif_url = '/exercise-demos/face-pull.mp4' WHERE name = 'Face Pull';
UPDATE exercises SET demo_gif_url = '/exercise-demos/barbell-back-squat.mp4' WHERE name = 'Barbell Back Squat';
UPDATE exercises SET demo_gif_url = '/exercise-demos/leg-press.mp4' WHERE name = 'Leg Press';
UPDATE exercises SET demo_gif_url = '/exercise-demos/romanian-deadlift.mp4' WHERE name = 'Romanian Deadlift';
UPDATE exercises SET demo_gif_url = '/exercise-demos/lying-leg-curl.mp4' WHERE name = 'Lying Leg Curl';
UPDATE exercises SET demo_gif_url = '/exercise-demos/leg-extension.mp4' WHERE name = 'Leg Extension';
UPDATE exercises SET demo_gif_url = '/exercise-demos/dumbbell-lunges.mp4' WHERE name = 'Dumbbell Lunges';
UPDATE exercises SET demo_gif_url = '/exercise-demos/walking-lunges.mp4' WHERE name = 'Walking Lunges';
UPDATE exercises SET demo_gif_url = '/exercise-demos/bulgarian-split-squat.mp4' WHERE name = 'Bulgarian Split Squat';
UPDATE exercises SET demo_gif_url = '/exercise-demos/hack-squat.mp4' WHERE name = 'Hack Squat';
UPDATE exercises SET demo_gif_url = '/exercise-demos/good-morning.mp4' WHERE name = 'Good Morning';
UPDATE exercises SET demo_gif_url = '/exercise-demos/seated-leg-curl.mp4' WHERE name = 'Seated Leg Curl';
UPDATE exercises SET demo_gif_url = '/exercise-demos/cable-pull-through.mp4' WHERE name = 'Cable Pull Through';
UPDATE exercises SET demo_gif_url = '/exercise-demos/glute-bridge.mp4' WHERE name = 'Glute Bridge';
UPDATE exercises SET demo_gif_url = '/exercise-demos/hip-thrust.mp4' WHERE name = 'Hip Thrust';
UPDATE exercises SET demo_gif_url = '/exercise-demos/calf-raise.mp4' WHERE name = 'Calf Raise';
UPDATE exercises SET demo_gif_url = '/exercise-demos/standing-calf-raise.mp4' WHERE name = 'Standing Calf Raise';
UPDATE exercises SET demo_gif_url = '/exercise-demos/seated-calf-raise.mp4' WHERE name = 'Seated Calf Raise';
UPDATE exercises SET demo_gif_url = '/exercise-demos/leg-press-calf-raise.mp4' WHERE name = 'Leg Press Calf Raise';
UPDATE exercises SET demo_gif_url = '/exercise-demos/barbell-curl.mp4' WHERE name = 'Barbell Curl';
UPDATE exercises SET demo_gif_url = '/exercise-demos/dumbbell-curl.mp4' WHERE name = 'Dumbbell Curl';
UPDATE exercises SET demo_gif_url = '/exercise-demos/hammer-curl.mp4' WHERE name = 'Hammer Curl';
UPDATE exercises SET demo_gif_url = '/exercise-demos/cable-curl.mp4' WHERE name = 'Cable Curl';
UPDATE exercises SET demo_gif_url = '/exercise-demos/incline-dumbbell-curl.mp4' WHERE name = 'Incline Dumbbell Curl';
UPDATE exercises SET demo_gif_url = '/exercise-demos/preacher-curl.mp4' WHERE name = 'Preacher Curl';
UPDATE exercises SET demo_gif_url = '/exercise-demos/tricep-pushdown.mp4' WHERE name = 'Tricep Pushdown';
UPDATE exercises SET demo_gif_url = '/exercise-demos/skull-crusher.mp4' WHERE name = 'Skull Crusher';
UPDATE exercises SET demo_gif_url = '/exercise-demos/close-grip-bench-press.mp4' WHERE name = 'Close Grip Bench Press';
UPDATE exercises SET demo_gif_url = '/exercise-demos/dips--tricep-focus-.mp4' WHERE name = 'Dips (Tricep Focus)';
UPDATE exercises SET demo_gif_url = '/exercise-demos/overhead-tricep-extension.mp4' WHERE name = 'Overhead Tricep Extension';
UPDATE exercises SET demo_gif_url = '/exercise-demos/cable-crunch.mp4' WHERE name = 'Cable Crunch';
UPDATE exercises SET demo_gif_url = '/exercise-demos/hanging-leg-raise.mp4' WHERE name = 'Hanging Leg Raise';
UPDATE exercises SET demo_gif_url = '/exercise-demos/ab-wheel-rollout.mp4' WHERE name = 'Ab Wheel Rollout';
UPDATE exercises SET demo_gif_url = '/exercise-demos/plank.mp4' WHERE name = 'Plank';
