-- SQL to update database with MuscleWiki videos
-- Run this in Supabase SQL Editor after downloading videos
-- Note: These are MP4 video files - update frontend to use <video> tags

UPDATE exercises SET demo_gif_url = '/exercise-demos/barbell-bench-press.mp4' WHERE name = 'Barbell Bench Press';
UPDATE exercises SET demo_gif_url = '/exercise-demos/dumbbell-bench-press.mp4' WHERE name = 'Dumbbell Bench Press';
UPDATE exercises SET demo_gif_url = '/exercise-demos/incline-dumbbell-press.mp4' WHERE name = 'Incline Dumbbell Press';
UPDATE exercises SET demo_gif_url = '/exercise-demos/cable-fly.mp4' WHERE name = 'Cable Fly';
UPDATE exercises SET demo_gif_url = '/exercise-demos/dips--chest-focus-.mp4' WHERE name = 'Dips (Chest Focus)';
UPDATE exercises SET demo_gif_url = '/exercise-demos/machine-chest-press.mp4' WHERE name = 'Machine Chest Press';
UPDATE exercises SET demo_gif_url = '/exercise-demos/barbell-row.mp4' WHERE name = 'Barbell Row';
UPDATE exercises SET demo_gif_url = '/exercise-demos/dumbbell-row.mp4' WHERE name = 'Dumbbell Row';
UPDATE exercises SET demo_gif_url = '/exercise-demos/lat-pulldown.mp4' WHERE name = 'Lat Pulldown';
UPDATE exercises SET demo_gif_url = '/exercise-demos/pull-ups.mp4' WHERE name = 'Pull-Ups';
UPDATE exercises SET demo_gif_url = '/exercise-demos/cable-row.mp4' WHERE name = 'Cable Row';
UPDATE exercises SET demo_gif_url = '/exercise-demos/deadlift.mp4' WHERE name = 'Deadlift';
UPDATE exercises SET demo_gif_url = '/exercise-demos/chest-supported-row.mp4' WHERE name = 'Chest Supported Row';
UPDATE exercises SET demo_gif_url = '/exercise-demos/overhead-press.mp4' WHERE name = 'Overhead Press';
UPDATE exercises SET demo_gif_url = '/exercise-demos/lateral-raise.mp4' WHERE name = 'Lateral Raise';
UPDATE exercises SET demo_gif_url = '/exercise-demos/rear-delt-fly.mp4' WHERE name = 'Rear Delt Fly';
UPDATE exercises SET demo_gif_url = '/exercise-demos/dumbbell-shoulder-press.mp4' WHERE name = 'Dumbbell Shoulder Press';
UPDATE exercises SET demo_gif_url = '/exercise-demos/face-pull.mp4' WHERE name = 'Face Pull';
UPDATE exercises SET demo_gif_url = '/exercise-demos/barbell-back-squat.mp4' WHERE name = 'Barbell Back Squat';
UPDATE exercises SET demo_gif_url = '/exercise-demos/leg-press.mp4' WHERE name = 'Leg Press';
UPDATE exercises SET demo_gif_url = '/exercise-demos/romanian-deadlift.mp4' WHERE name = 'Romanian Deadlift';
UPDATE exercises SET demo_gif_url = '/exercise-demos/lying-leg-curl.mp4' WHERE name = 'Lying Leg Curl';
UPDATE exercises SET demo_gif_url = '/exercise-demos/leg-extension.mp4' WHERE name = 'Leg Extension';
UPDATE exercises SET demo_gif_url = '/exercise-demos/dumbbell-lunges.mp4' WHERE name = 'Dumbbell Lunges';
UPDATE exercises SET demo_gif_url = '/exercise-demos/walking-lunges.mp4' WHERE name = 'Walking Lunges';
UPDATE exercises SET demo_gif_url = '/exercise-demos/bulgarian-split-squat.mp4' WHERE name = 'Bulgarian Split Squat';
UPDATE exercises SET demo_gif_url = '/exercise-demos/hack-squat.mp4' WHERE name = 'Hack Squat';
UPDATE exercises SET demo_gif_url = '/exercise-demos/good-morning.mp4' WHERE name = 'Good Morning';
UPDATE exercises SET demo_gif_url = '/exercise-demos/seated-leg-curl.mp4' WHERE name = 'Seated Leg Curl';
UPDATE exercises SET demo_gif_url = '/exercise-demos/cable-pull-through.mp4' WHERE name = 'Cable Pull Through';
UPDATE exercises SET demo_gif_url = '/exercise-demos/glute-bridge.mp4' WHERE name = 'Glute Bridge';
UPDATE exercises SET demo_gif_url = '/exercise-demos/hip-thrust.mp4' WHERE name = 'Hip Thrust';
UPDATE exercises SET demo_gif_url = '/exercise-demos/calf-raise.mp4' WHERE name = 'Calf Raise';
UPDATE exercises SET demo_gif_url = '/exercise-demos/standing-calf-raise.mp4' WHERE name = 'Standing Calf Raise';
UPDATE exercises SET demo_gif_url = '/exercise-demos/seated-calf-raise.mp4' WHERE name = 'Seated Calf Raise';
UPDATE exercises SET demo_gif_url = '/exercise-demos/leg-press-calf-raise.mp4' WHERE name = 'Leg Press Calf Raise';
UPDATE exercises SET demo_gif_url = '/exercise-demos/barbell-curl.mp4' WHERE name = 'Barbell Curl';
UPDATE exercises SET demo_gif_url = '/exercise-demos/dumbbell-curl.mp4' WHERE name = 'Dumbbell Curl';
UPDATE exercises SET demo_gif_url = '/exercise-demos/hammer-curl.mp4' WHERE name = 'Hammer Curl';
UPDATE exercises SET demo_gif_url = '/exercise-demos/cable-curl.mp4' WHERE name = 'Cable Curl';
UPDATE exercises SET demo_gif_url = '/exercise-demos/incline-dumbbell-curl.mp4' WHERE name = 'Incline Dumbbell Curl';
UPDATE exercises SET demo_gif_url = '/exercise-demos/preacher-curl.mp4' WHERE name = 'Preacher Curl';
UPDATE exercises SET demo_gif_url = '/exercise-demos/tricep-pushdown.mp4' WHERE name = 'Tricep Pushdown';
UPDATE exercises SET demo_gif_url = '/exercise-demos/skull-crusher.mp4' WHERE name = 'Skull Crusher';
UPDATE exercises SET demo_gif_url = '/exercise-demos/close-grip-bench-press.mp4' WHERE name = 'Close Grip Bench Press';
UPDATE exercises SET demo_gif_url = '/exercise-demos/dips--tricep-focus-.mp4' WHERE name = 'Dips (Tricep Focus)';
UPDATE exercises SET demo_gif_url = '/exercise-demos/overhead-tricep-extension.mp4' WHERE name = 'Overhead Tricep Extension';
UPDATE exercises SET demo_gif_url = '/exercise-demos/cable-crunch.mp4' WHERE name = 'Cable Crunch';
UPDATE exercises SET demo_gif_url = '/exercise-demos/hanging-leg-raise.mp4' WHERE name = 'Hanging Leg Raise';
UPDATE exercises SET demo_gif_url = '/exercise-demos/ab-wheel-rollout.mp4' WHERE name = 'Ab Wheel Rollout';
UPDATE exercises SET demo_gif_url = '/exercise-demos/plank.mp4' WHERE name = 'Plank';
UPDATE exercises SET demo_gif_url = '/exercise-demos/pec-deck.mp4' WHERE name = 'Pec Deck';
UPDATE exercises SET demo_gif_url = '/exercise-demos/smith-machine-bench-press.mp4' WHERE name = 'Smith Machine Bench Press';
UPDATE exercises SET demo_gif_url = '/exercise-demos/smith-machine-incline-press.mp4' WHERE name = 'Smith Machine Incline Press';
UPDATE exercises SET demo_gif_url = '/exercise-demos/decline-barbell-press.mp4' WHERE name = 'Decline Barbell Press';
UPDATE exercises SET demo_gif_url = '/exercise-demos/seated-machine-row.mp4' WHERE name = 'Seated Machine Row';
UPDATE exercises SET demo_gif_url = '/exercise-demos/assisted-pull-up-machine.mp4' WHERE name = 'Assisted Pull-Up Machine';
UPDATE exercises SET demo_gif_url = '/exercise-demos/back-extension.mp4' WHERE name = 'Back Extension';
UPDATE exercises SET demo_gif_url = '/exercise-demos/meadows-row.mp4' WHERE name = 'Meadows Row';
UPDATE exercises SET demo_gif_url = '/exercise-demos/assisted-pull-up.mp4' WHERE name = 'Assisted Pull-Up';
UPDATE exercises SET demo_gif_url = '/exercise-demos/rear-delt-machine.mp4' WHERE name = 'Rear Delt Machine';
UPDATE exercises SET demo_gif_url = '/exercise-demos/machine-lateral-raise.mp4' WHERE name = 'Machine Lateral Raise';
UPDATE exercises SET demo_gif_url = '/exercise-demos/upright-row.mp4' WHERE name = 'Upright Row';
UPDATE exercises SET demo_gif_url = '/exercise-demos/cable-upright-row.mp4' WHERE name = 'Cable Upright Row';
UPDATE exercises SET demo_gif_url = '/exercise-demos/front-raise.mp4' WHERE name = 'Front Raise';
UPDATE exercises SET demo_gif_url = '/exercise-demos/behind-the-back-cable-lateral-raise.mp4' WHERE name = 'Behind-the-Back Cable Lateral Raise';
UPDATE exercises SET demo_gif_url = '/exercise-demos/cable-y-raise.mp4' WHERE name = 'Cable Y-Raise';
UPDATE exercises SET demo_gif_url = '/exercise-demos/reverse-cable-crossover.mp4' WHERE name = 'Reverse Cable Crossover';
UPDATE exercises SET demo_gif_url = '/exercise-demos/barbell-shrug.mp4' WHERE name = 'Barbell Shrug';
UPDATE exercises SET demo_gif_url = '/exercise-demos/machine-bicep-curl.mp4' WHERE name = 'Machine Bicep Curl';
UPDATE exercises SET demo_gif_url = '/exercise-demos/concentration-curl.mp4' WHERE name = 'Concentration Curl';
UPDATE exercises SET demo_gif_url = '/exercise-demos/ez-bar-curl.mp4' WHERE name = 'EZ Bar Curl';
UPDATE exercises SET demo_gif_url = '/exercise-demos/bayesian-cable-curl.mp4' WHERE name = 'Bayesian Cable Curl';
UPDATE exercises SET demo_gif_url = '/exercise-demos/45--preacher-curl.mp4' WHERE name = '45° Preacher Curl';
UPDATE exercises SET demo_gif_url = '/exercise-demos/cable-bicep-curl.mp4' WHERE name = 'Cable Bicep Curl';
UPDATE exercises SET demo_gif_url = '/exercise-demos/machine-tricep-extension.mp4' WHERE name = 'Machine Tricep Extension';
UPDATE exercises SET demo_gif_url = '/exercise-demos/rope-tricep-pushdown.mp4' WHERE name = 'Rope Tricep Pushdown';
UPDATE exercises SET demo_gif_url = '/exercise-demos/assisted-dip-machine.mp4' WHERE name = 'Assisted Dip Machine';
UPDATE exercises SET demo_gif_url = '/exercise-demos/dumbbell-kickback.mp4' WHERE name = 'Dumbbell Kickback';
UPDATE exercises SET demo_gif_url = '/exercise-demos/cable-overhead-tricep-extension.mp4' WHERE name = 'Cable Overhead Tricep Extension';
UPDATE exercises SET demo_gif_url = '/exercise-demos/cable-tricep-pushdown.mp4' WHERE name = 'Cable Tricep Pushdown';
UPDATE exercises SET demo_gif_url = '/exercise-demos/smith-machine-squat.mp4' WHERE name = 'Smith Machine Squat';
UPDATE exercises SET demo_gif_url = '/exercise-demos/pendulum-squat.mp4' WHERE name = 'Pendulum Squat';
UPDATE exercises SET demo_gif_url = '/exercise-demos/sissy-squat.mp4' WHERE name = 'Sissy Squat';
UPDATE exercises SET demo_gif_url = '/exercise-demos/reverse-lunge.mp4' WHERE name = 'Reverse Lunge';
UPDATE exercises SET demo_gif_url = '/exercise-demos/step-up.mp4' WHERE name = 'Step Up';
UPDATE exercises SET demo_gif_url = '/exercise-demos/stiff-leg-deadlift.mp4' WHERE name = 'Stiff Leg Deadlift';
UPDATE exercises SET demo_gif_url = '/exercise-demos/single-leg-rdl.mp4' WHERE name = 'Single Leg RDL';
UPDATE exercises SET demo_gif_url = '/exercise-demos/nordic-curl.mp4' WHERE name = 'Nordic Curl';
UPDATE exercises SET demo_gif_url = '/exercise-demos/glute-drive-machine.mp4' WHERE name = 'Glute Drive Machine';
UPDATE exercises SET demo_gif_url = '/exercise-demos/hip-abduction-machine.mp4' WHERE name = 'Hip Abduction Machine';
UPDATE exercises SET demo_gif_url = '/exercise-demos/hip-adduction-machine.mp4' WHERE name = 'Hip Adduction Machine';
UPDATE exercises SET demo_gif_url = '/exercise-demos/single-leg-hip-thrust.mp4' WHERE name = 'Single Leg Hip Thrust';
UPDATE exercises SET demo_gif_url = '/exercise-demos/sumo-deadlift.mp4' WHERE name = 'Sumo Deadlift';
UPDATE exercises SET demo_gif_url = '/exercise-demos/smith-machine-calf-raise.mp4' WHERE name = 'Smith Machine Calf Raise';
UPDATE exercises SET demo_gif_url = '/exercise-demos/donkey-calf-raise.mp4' WHERE name = 'Donkey Calf Raise';
UPDATE exercises SET demo_gif_url = '/exercise-demos/calf-press-machine.mp4' WHERE name = 'Calf Press Machine';
UPDATE exercises SET demo_gif_url = '/exercise-demos/pallof-press.mp4' WHERE name = 'Pallof Press';
UPDATE exercises SET demo_gif_url = '/exercise-demos/dead-bug.mp4' WHERE name = 'Dead Bug';
UPDATE exercises SET demo_gif_url = '/exercise-demos/russian-twist.mp4' WHERE name = 'Russian Twist';
UPDATE exercises SET demo_gif_url = '/exercise-demos/cable-woodchop.mp4' WHERE name = 'Cable Woodchop';
UPDATE exercises SET demo_gif_url = '/exercise-demos/hammer-strength-ab-crunch.mp4' WHERE name = 'Hammer Strength Ab Crunch';
UPDATE exercises SET demo_gif_url = '/exercise-demos/farmer-s-carry.mp4' WHERE name = 'Farmer''s Carry';
UPDATE exercises SET demo_gif_url = '/exercise-demos/suitcase-carry.mp4' WHERE name = 'Suitcase Carry';
