// ============================================================
// SHARED MESOCYCLE WORKOUT-START PATH
//
// Both the Mesocycle page (app/(dashboard)/dashboard/mesocycle/page.tsx)
// and the Train page's mesocycle tab (app/(dashboard)/dashboard/workout/
// page.tsx) start "today's workout" from the active mesocycle. This module
// owns that logic so the two entry points cannot drift:
//
//   1. Resume today's existing planned/in-progress session if there is one —
//      EXCEPT a blockless `planned` shell belonging to this mesocycle (a
//      schedule placeholder, e.g. regenerated by the /mesocycle training-day
//      editor), which is claimed instead: flipped to in_progress and filled
//      with blocks via steps 3-4.
//   2. Otherwise create a workout_sessions row for today.
//   3. Build exercise blocks from mesocycle.program_data via
//      getSessionFromProgramData (day = TOTAL completed sessions modulo
//      days/week, so skipped days — even across calendar weeks — never drop
//      a session; the plan self-extends), applying:
//        - exercise_overrides (user's swapped exercises),
//        - weekly progression modifiers (intensity/deload),
//        - weekly per-muscle set adjustments from last week's feedback
//          (lib/training/weeklyRollover),
//        - weight estimation (quickWeightEstimate) and warmup protocols.
//   4. FALLBACK: when program_data yields no usable blocks (mesocycles
//      created before program_data existed, or exercise names that don't
//      match the library), build the session from today's target muscles
//      with the legacy defaults (2 exercises per muscle, 4 sets compound /
//      3 isolation, halved on deload).
//
// Pages keep their own UX (loading state, error handling, router.push);
// this module returns the session id to navigate to.
// ============================================================

import type { SupabaseClient } from '@supabase/supabase-js';
import { getLocalDateString } from '@/lib/utils';
import { generateWarmupProtocol } from '@/services/progressionEngine';
import {
  getSessionFromProgramData,
  getWeekSessionsFromProgramData,
  getWeeklyProgressionModifiers,
  applyExerciseOverrides,
  type ExerciseOverride,
  type ExtractedSession,
} from '@/services/mesocycleHelpers';
import {
  planWeeklySetAdjustments,
  loadWeeklyMuscleSignals,
  resolveVolumeLandmarks,
  exerciseKey,
  type WeeklyAdjustmentPlan,
} from '@/lib/training/weeklyRollover';
import { readLandmarkVersion } from '@/lib/migrations/volume-landmarks';
import { sessionIndexFromCompleted } from '@/lib/training/mesocycleProgress';
import {
  getTrainingDays,
  getWorkoutForDate,
  getWorkoutForDay,
  getWorkoutsForDate,
  getNextWorkoutForDate,
  type TodayWorkout,
} from '@/lib/training/trainingSchedule';
import { insertWorkoutSessions } from '@/lib/training/sessionOrigin';
import { resolveDefaultLocationId, updateSessionLocation } from '@/lib/training/sessionLocation';
import { quickWeightEstimate, type TransferCandidate } from '@/services/weightEstimationEngine';
import { fetchTransferCandidates } from '@/lib/training/transferCandidates';
import {
  bestQualifyingE1RM,
  historySetE1RM,
  type AnchorCandidate,
} from '@/services/suggestionEngine/e1rmAnchor';
import { HISTORY_SESSIONS_PER_EXERCISE } from '@/services/suggestionEngine/constants';
import { recommendSeedForSlot, type PrevSessionSet } from '@/services/setRecommender';
import { rpeToRir, toLegacyMuscleGroup } from '@/types/schema';
import type {
  Experience,
  FullProgramRecommendation,
  MuscleGroup,
  WarmupSet,
} from '@/types/schema';
import { now as clockNow } from '@/lib/clock';

// ============================================================
// Types
// ============================================================

export type Goal = 'bulk' | 'cut' | 'maintain';

export type { TodayWorkout };

/** The mesocycle fields the start path needs (subset of the pages' row shape). */
export interface StartableMesocycle {
  id: string;
  current_week: number;
  total_weeks: number;
  deload_week: number;
  days_per_week: number;
  program_data: unknown;
  exercise_overrides?: ExerciseOverride[];
  /**
   * Enhanced Athlete Mode at (re)generation time. In-flight weekly
   * progression follows THIS tag, not the live profile flag — so choosing
   * "Apply at next mesocycle" after a toggle really leaves the current meso
   * unchanged. NULL (pre-feature mesos) falls back to the live flag.
   */
  generated_with_enhanced_mode?: boolean | null;
}

export interface StartMesocycleSessionInput {
  supabase: SupabaseClient;
  mesocycle: StartableMesocycle;
  /** Today's scheduled workout (used by the no-program_data fallback). */
  todayWorkout: TodayWorkout | null;
  /**
   * TOTAL completed sessions for this mesocycle. The session index is
   * `completedSessions % days_per_week`, so skipped days (even across
   * calendar-week boundaries) never drop a session — the user always resumes
   * at the next un-done slot. When omitted it is queried from the database.
   */
  completedSessions?: number;
}

export interface StartMesocycleSessionResult {
  sessionId: string;
  /** True when an existing planned/in-progress session for today was reused. */
  resumedExisting: boolean;
}

interface ExerciseBlockInsert {
  workout_session_id: string;
  exercise_id: string;
  order: number;
  target_sets: number;
  target_rep_range: number[];
  target_rir: number;
  target_weight_kg: number;
  target_rest_seconds: number;
  suggestion_reason: string;
  warmup_protocol: { sets: WarmupSet[] };
}

// ============================================================
// Scheduling helpers (shared by both pages)
//
// The calendar lives in lib/training/trainingSchedule (pure, dependency-free)
// so fixed-weekday and every-N-days schedules resolve identically everywhere
// — and so surfaces that only need "what's scheduled today" (the dashboard)
// don't pull this module's session-building dependencies into their bundle.
// Re-exported here because both workout-start pages import them alongside
// startMesocycleWorkoutSession.
// ============================================================

export { getTrainingDays, getWorkoutForDate, getWorkoutForDay, getWorkoutsForDate, getNextWorkoutForDate };

/**
 * Get rest period based on exercise type and user's goal
 * - Compound exercises need more rest for recovery
 * - Cutting: shorter rest for metabolic demand
 * - Bulking: full rest for maximum performance
 */
export function getRestPeriod(isCompound: boolean, goal: Goal, primaryMuscle?: MuscleGroup): number {
  // Ab exercises need shorter rest periods (recover faster); 'obliques'
  // primaries (Pallof press, Russian twist) count as ab work too.
  if (primaryMuscle && toLegacyMuscleGroup(primaryMuscle) === 'abs') {
    return goal === 'cut' ? 30 : 45;
  }

  if (goal === 'cut') {
    return isCompound ? 120 : 60;  // 2min / 1min
  }
  if (goal === 'bulk') {
    return isCompound ? 180 : 90;  // 3min / 1.5min
  }
  // maintain
  return isCompound ? 150 : 75;    // 2.5min / 1.25min
}

/**
 * TOTAL completed sessions for a mesocycle. Progression is session-count
 * based (see lib/training/mesocycleProgress.ts): the week is
 * floor(count / daysPerWeek) + 1 and the session index is
 * count % daysPerWeek, so the plan self-extends when days are skipped
 * instead of dropping the rest of a calendar week.
 */
export async function countCompletedSessions(
  supabase: SupabaseClient,
  mesocycleId: string
): Promise<number> {
  const { count } = await supabase
    .from('workout_sessions')
    .select('id', { count: 'exact', head: true })
    .eq('mesocycle_id', mesocycleId)
    .eq('state', 'completed');

  return count || 0;
}

/**
 * Completed sessions on ONE calendar date — how far through a two-a-day
 * date's slots the user is. Feeds getNextWorkoutForDate so "today's workout"
 * surfaces advance to the PM session once the AM one is finished.
 */
export async function countCompletedSessionsOnDate(
  supabase: SupabaseClient,
  mesocycleId: string,
  dateStr: string
): Promise<number> {
  const { count } = await supabase
    .from('workout_sessions')
    .select('id', { count: 'exact', head: true })
    .eq('mesocycle_id', mesocycleId)
    .eq('state', 'completed')
    .eq('planned_date', dateStr);

  return count || 0;
}

/**
 * Older mesocycles stored placeholder ids (e.g. "db-row") in program_data;
 * only a real UUID can satisfy the exercise_blocks.exercise_id FK.
 */
const isUuid = (v: unknown): v is string =>
  typeof v === 'string' &&
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(v);

/** Row shape of the per-exercise direct-history query below. */
interface DirectHistoryRow {
  id: string;
  exercise_blocks:
    | {
        workout_sessions: {
          id: string;
          completed_at: string | null;
          is_deload: boolean | null;
        } | null;
        set_logs:
          | {
              weight_kg: number | null;
              reps: number | null;
              rpe: number | null;
              is_warmup: boolean | null;
              set_number: number | null;
              set_type: string | null;
              logged_at: string | null;
            }[]
          | null;
      }[]
    | null;
}

/**
 * One exercise's direct history reduced to the same inputs the live card's
 * session-start recommender consumes, so the persisted block target goes
 * through the SAME gates (±10% working-weight clamp, all-sets bump gate,
 * confirmed-regression step-down) as the on-screen seed.
 */
interface DirectHistorySummary {
  /** Recency-decayed e1RM anchor (decayedE1RMMax over non-deload sets). */
  anchorE1RMKg: number;
  /** Top working weight of the most recent non-deload session (clamp anchor). */
  recentWorkingWeightKg: number;
  /** Working sets of the most recent non-deload session, performed order. */
  prevSessionSets: PrevSessionSet[];
  /** Working sets of the session before that ([] when none). */
  priorSessionSets: PrevSessionSet[];
}

/**
 * Anchor candidates from one exercise's history row: non-deload sessions,
 * non-warmup NORMAL sets only (cluster/myorep/rest-pause/dropset reps never
 * enter the pool — same eligibility rule as the workout page's
 * isAnchorEligibleSet), each with a non-null canonical estimate.
 */
function anchorCandidatesFromHistoryRow(row: DirectHistoryRow): AnchorCandidate[] {
  const candidates: AnchorCandidate[] = [];
  for (const block of row.exercise_blocks ?? []) {
    const session = block.workout_sessions;
    // Deload sessions are held light on purpose — never anchor on them.
    if (!session || session.is_deload) continue;
    for (const s of block.set_logs ?? []) {
      const weightKg = s.weight_kg ?? 0;
      const reps = s.reps ?? 0;
      if (s.is_warmup || weightKg <= 0 || reps <= 0) continue;
      if ((s.set_type ?? 'normal') !== 'normal') continue;
      // NULL = beyond the canonical estimator's domain (effective reps > 15):
      // the set is not an e1RM data point and never enters the anchor pool.
      const estimate = historySetE1RM(weightKg, reps, s.rpe ?? 10);
      if (!estimate) continue;
      candidates.push({
        e1rmKg: estimate.value,
        sessionId: session.id,
        timeMs: Date.parse(session.completed_at || s.logged_at || ''),
      });
    }
  }
  return candidates;
}

/**
 * Normal working sets of one history block, ordered by set_number — the same
 * filtering buildExerciseHistories applies to lastWorkoutSets.
 */
function workingSetsFromBlock(
  block: NonNullable<DirectHistoryRow['exercise_blocks']>[number]
): PrevSessionSet[] {
  return (block.set_logs ?? [])
    .filter((s) => !s.is_warmup && (s.set_type ?? 'normal') === 'normal')
    .sort((a, b) => (a.set_number ?? 0) - (b.set_number ?? 0))
    .filter((s) => (s.weight_kg ?? 0) > 0 && (s.reps ?? 0) > 0)
    .map((s) => ({
      weightKg: s.weight_kg as number,
      reps: s.reps as number,
      rir: s.rpe != null ? Math.max(0, rpeToRir(s.rpe)) : undefined,
    }));
}

/** The last two non-deload sessions' working sets + the recent top weight. */
function recentSessionsFromHistoryRow(row: DirectHistoryRow): {
  recentWorkingWeightKg: number;
  prevSessionSets: PrevSessionSet[];
  priorSessionSets: PrevSessionSet[];
} {
  const nonDeload = (row.exercise_blocks ?? []).filter(
    (b) => b.workout_sessions && !b.workout_sessions.is_deload
  );
  // "Last session" = the most recent block that actually HAS working sets: a
  // completed session can hold an empty block for this exercise (skipped that
  // day, or never logged), and anchoring on it would drop the clamp/bump-gate
  // inputs while real history sits one session back. Mirrors the live card's
  // computeHistoryFromBlocks fallback.
  const lastBlock = nonDeload.find((b) => workingSetsFromBlock(b).length > 0);
  const lastSessionId = lastBlock?.workout_sessions?.id;
  const priorBlock = nonDeload.find(
    (b) =>
      b.workout_sessions?.id !== lastSessionId && workingSetsFromBlock(b).length > 0
  );
  const prevSessionSets = lastBlock ? workingSetsFromBlock(lastBlock) : [];
  const priorSessionSets = priorBlock ? workingSetsFromBlock(priorBlock) : [];
  return {
    recentWorkingWeightKg: prevSessionSets.reduce((m, s) => (s.weightKg > m ? s.weightKg : m), 0),
    prevSessionSets,
    priorSessionSets,
  };
}

/**
 * Direct-history summary per exercise (audit remediation Fix 5). One batched
 * query — the same per-exercise embedded last-N window the workout page's
 * history read uses — reduced to the recency-decayed e1RM anchor (same
 * Brzycki-with-RIR per-set formula as the live card) PLUS the last two
 * sessions' working sets, so the block target can run through the live
 * session-start gates. Exercises with no direct history are simply absent
 * from the map; any query failure degrades to an empty map so the cold-start
 * estimation ladder still runs.
 */
async function fetchDirectHistoryAnchors(
  supabase: SupabaseClient,
  userId: string,
  exerciseIds: string[]
): Promise<Map<string, DirectHistorySummary>> {
  const anchors = new Map<string, DirectHistorySummary>();
  if (exerciseIds.length === 0) return anchors;
  try {
    const { data, error } = await supabase
      .from('exercises')
      .select(
        `
        id,
        exercise_blocks (
          workout_sessions!inner (
            id,
            completed_at,
            is_deload
          ),
          set_logs (
            weight_kg,
            reps,
            rpe,
            is_warmup,
            set_number,
            set_type,
            logged_at
          )
        )
      `
      )
      .in('id', exerciseIds)
      .eq('exercise_blocks.workout_sessions.user_id', userId)
      .eq('exercise_blocks.workout_sessions.state', 'completed')
      .order('workout_sessions(completed_at)', {
        referencedTable: 'exercise_blocks',
        ascending: false,
      })
      .limit(HISTORY_SESSIONS_PER_EXERCISE, { referencedTable: 'exercise_blocks' });

    if (error || !data) return anchors;

    // (The generated client types infer to-one embeds as arrays — cast via
    // unknown to the runtime shape, same convention as the workout page.)
    for (const row of data as unknown as DirectHistoryRow[]) {
      const anchorE1RMKg = bestQualifyingE1RM(anchorCandidatesFromHistoryRow(row));
      if (anchorE1RMKg > 0) {
        anchors.set(row.id, { anchorE1RMKg, ...recentSessionsFromHistoryRow(row) });
      }
    }
  } catch {
    // Non-fatal: fall through to the estimation ladder.
  }
  return anchors;
}

/**
 * Whether a program_data session would actually produce exercise blocks in
 * startMesocycleWorkoutSession. Mirrors the block-building skip logic there:
 * an entry is buildable when its stored exerciseId is a real UUID, or its
 * name (after the user's exercise overrides) resolves in the exercises table.
 * When nothing is buildable the start path falls back to the calendar
 * workout, so surfaces advertising "what Start launches" must fall back under
 * this same check — a bare exercises.length test would advertise stale
 * programs (deleted/renamed exercises) whose slot Start won't launch.
 */
export async function programSessionHasUsableExercises(
  supabase: SupabaseClient,
  session: ExtractedSession | null,
  overrides?: ExerciseOverride[] | null
): Promise<boolean> {
  if (!session || session.exercises.length === 0) return false;

  const exercises = applyExerciseOverrides(session.exercises, overrides ?? []);
  const unresolvedNames: string[] = [];
  for (const exercise of exercises) {
    if (isUuid(exercise.exerciseId)) return true;
    unresolvedNames.push(exercise.exerciseName);
  }

  const { data } = await supabase
    .from('exercises')
    .select('id')
    .in('name', unresolvedNames)
    .is('deleted_at', null) // hide merge-soft-deleted duplicates
    .limit(1);
  return (data?.length ?? 0) > 0;
}

// ============================================================
// Start path
// ============================================================

/**
 * Start today's workout from the active mesocycle. Creates the session and
 * exercise blocks (or resumes today's existing session) and returns the
 * session id to navigate to. Throws on unrecoverable failures; callers own
 * loading state and navigation.
 */
export async function startMesocycleWorkoutSession(
  input: StartMesocycleSessionInput
): Promise<StartMesocycleSessionResult> {
  const { supabase, mesocycle, todayWorkout } = input;

  const { data: { user } } = await supabase.auth.getUser();

  if (!user) throw new Error('Not logged in');

  // Fetch user profile for goal and weight estimation
  const { data: userProfile } = await supabase
    .from('user_profiles')
    .select('goal, experience')
    .eq('user_id', user.id)
    .single();

  const { data: userData } = await supabase
    .from('users')
    .select('height_cm, weight_kg, body_fat_percent, experience, volume_landmarks, enhanced_athlete_mode, preferences')
    .eq('id', user.id)
    .single();

  const userGoal: Goal = (userProfile?.goal as Goal) || 'maintain';
  const userExperience = (userData?.experience || userProfile?.experience || 'intermediate') as Experience;

  // Check if there's already a workout for today
  const today = getLocalDateString();
  const { data: existingWorkout } = await supabase
    .from('workout_sessions')
    .select('id, state, mesocycle_id')
    .eq('user_id', user.id)
    .eq('planned_date', today)
    .in('state', ['planned', 'in_progress'])
    .single();

  // A `planned` row for this mesocycle with NO exercise blocks is a schedule
  // shell (e.g. regenerated by the /mesocycle training-day editor), not a
  // resumable workout — resuming it would open an empty session and, because
  // it occupies today's date, permanently block a real one from being built.
  // Claim it instead: flip it to in_progress below and build blocks into it.
  // Planned rows WITH blocks (workouts built ahead of time) and in-progress
  // sessions resume as before.
  let claimedShellId: string | null = null;
  if (existingWorkout) {
    if (existingWorkout.state === 'planned' && existingWorkout.mesocycle_id === mesocycle.id) {
      const { count: blockCount } = await supabase
        .from('exercise_blocks')
        .select('id', { count: 'exact', head: true })
        .eq('workout_session_id', existingWorkout.id);
      if (!blockCount) claimedShellId = existingWorkout.id;
    }
    if (!claimedShellId) {
      // Resume existing workout
      return { sessionId: existingWorkout.id, resumedExisting: true };
    }
  }

  const completedSessions =
    input.completedSessions ?? (await countCompletedSessions(supabase, mesocycle.id));

  // Cross-exercise strength summary for cold-start weight estimation: a
  // never-trained exercise seeds from a related exercise's logged e1RM
  // (same pattern → same muscle) before falling back to profile heuristics.
  const transferCandidates: TransferCandidate[] = await fetchTransferCandidates(user.id, supabase);

  // Create new workout session (or claim today's blockless planned shell)
  let sessionId: string;
  if (claimedShellId) {
    // Claim atomically: only flip the row if it's still a planned shell for
    // this mesocycle. Two concurrent starts (double tap, second tab) can both
    // pass the zero-block check above; without this filter both updates
    // succeed and both callers insert blocks, duplicating every exercise.
    const { data: claimedRows, error: claimError } = await supabase
      .from('workout_sessions')
      .update({ state: 'in_progress', started_at: clockNow().toISOString() })
      .eq('id', claimedShellId)
      .eq('state', 'planned')
      .eq('mesocycle_id', mesocycle.id)
      .select('id');

    if (claimError) throw claimError;
    if (!claimedRows || claimedRows.length === 0) {
      // Lost the race — the other start owns the shell and is building its
      // blocks. Resume into it rather than inserting a second set.
      return { sessionId: claimedShellId, resumedExisting: true };
    }
    sessionId = claimedShellId;

    // A planned shell was written by the schedule editor, which has no
    // location to give it — so stamp one now, same as a fresh insert. No sets
    // exist yet (that's what made it a shell), hence nothing to re-stamp.
    const shellLocationId = await resolveDefaultLocationId(supabase, user.id);
    if (shellLocationId) {
      await updateSessionLocation(supabase, {
        sessionId,
        locationId: shellLocationId,
        previousLocationId: null,
        blockIdsToRestamp: [],
      });
    }
  } else {
    // Scheduled sessions carry a location like builder-started ones do.
    // Without this every mesocycle session was locationless, so machine loads
    // from different gyms shared one history — the conflation location-scoped
    // calibration exists to prevent. Wrong on a travel day; the in-workout
    // header chip fixes it in one tap and re-files the sets already logged.
    const defaultLocationId = await resolveDefaultLocationId(supabase, user.id);

    const { data: sessions, error: sessionError } = await insertWorkoutSessions(supabase, [
      {
        user_id: user.id,
        mesocycle_id: mesocycle.id,
        planned_date: today,
        state: 'in_progress',
        started_at: clockNow().toISOString(),
        completion_percent: 0,
        origin: 'scheduled' as const,
        location_id: defaultLocationId,
      },
    ]);

    const session = sessions?.[0];
    if (sessionError || !session) throw sessionError || new Error('Failed to create session');
    sessionId = session.id;
  }

  // Try to get session from program_data first (preferred - uses pre-calculated exercises & sets)
  // Session index = TOTAL completed % days/week, so skipped days (even across
  // calendar-week boundaries) never drop a session — e.g. a user who finished
  // 2 of 4 sessions last week resumes at session 2, not week N+1 session 0.
  const programData = mesocycle.program_data as FullProgramRecommendation | null;
  const sessionIndex = sessionIndexFromCompleted(completedSessions, mesocycle.days_per_week);
  const programSession = getSessionFromProgramData(
    programData,
    sessionIndex,
    mesocycle.current_week,
    mesocycle.total_weeks
  );

  // Get weekly progression modifiers for intensity/volume adjustments
  const progressionModifiers = getWeeklyProgressionModifiers(
    programData,
    mesocycle.current_week
  );

  // Auto-flag as a deload session when it's generated during a programmed
  // deload week, so all the deload-exclusion consumers (suggestions, e1RM/PR
  // trends, stagnation baselines, adaptive volume) skip it without the user
  // having to remember to toggle it. The user can still override via the
  // finish/summary toggle or retroactively from history.
  if (progressionModifiers.isDeload) {
    const { error: deloadFlagError } = await supabase
      .from('workout_sessions')
      .update({ is_deload: true })
      .eq('id', sessionId);
    if (deloadFlagError) {
      // Non-fatal: the session is still usable, it just won't be auto-excluded.
      console.error('Failed to flag session as deload:', deloadFlagError);
    }
  }

  // Weekly auto-regulation (Phase 1.2): react to last week's per-muscle
  // feedback (session_muscle_feedback) + performance trend by adding or
  // removing one set on the last exercise targeting each muscle in this
  // week's plan. With no feedback rows the engine holds everywhere and
  // the plan stays empty, so generation is identical to before.
  const weekSessions = getWeekSessionsFromProgramData(programData, mesocycle.current_week);
  const weekSessionIdx = weekSessions.length > 0 ? sessionIndex % weekSessions.length : 0;
  let weeklyAdjustmentPlan: WeeklyAdjustmentPlan | null = null;
  if (
    weekSessions.length > 0 &&
    programSession !== null &&
    programSession.exercises.length > 0 &&
    !progressionModifiers.isDeload
  ) {
    try {
      const signals = await loadWeeklyMuscleSignals(supabase, user.id, mesocycle.id);
      // The meso's generation-time mode governs in-flight progression; the
      // live profile flag only applies when the meso predates the tag.
      const enhancedAthleteMode =
        mesocycle.generated_with_enhanced_mode ??
        (userData?.enhanced_athlete_mode === true);
      weeklyAdjustmentPlan = planWeeklySetAdjustments({
        weekSessions,
        feedbackByMuscle: signals.feedbackByMuscle,
        trendByMuscle: signals.trendByMuscle,
        landmarksByMuscle: resolveVolumeLandmarks(
          userExperience,
          (userData?.volume_landmarks as Record<string, unknown> | null) ?? null,
          enhancedAthleteMode,
          readLandmarkVersion(
            (userData?.preferences as Record<string, unknown> | null) ?? null
          )
        ),
        weekInMeso: mesocycle.current_week,
        isDeloadWeek: mesocycle.current_week === mesocycle.deload_week,
        enhancedAthleteMode,
      });
    } catch (adjustmentError) {
      // Non-fatal: fall back to the unadjusted program.
      console.error('Weekly set adjustment failed, using program as-is:', adjustmentError);
    }
  }

  const blocks: ExerciseBlockInsert[] = [];
  let order = 1;
  const seenMuscles = new Set<string>();

  if (programSession && programSession.exercises.length > 0) {
    // Apply any exercise overrides (user's swapped exercises)
    const overrides = (mesocycle.exercise_overrides || []) as ExerciseOverride[];
    const exercisesWithOverrides = applyExerciseOverrides(programSession.exercises, overrides);

    // Direct-history anchors (Fix 5): resolve today's exercise ids up front
    // (program UUIDs + one batched name lookup) and batch-fetch each one's
    // own recent history, so target_weight_kg can come from the user's real
    // e1RM instead of the population/transfer estimate whenever they have
    // trained the exercise before.
    const uuidIds = exercisesWithOverrides
      .map((e) => e.exerciseId)
      .filter(isUuid);
    const unresolvedNames = exercisesWithOverrides
      .filter((e) => !isUuid(e.exerciseId))
      .map((e) => e.exerciseName);
    let nameResolvedIds: string[] = [];
    if (unresolvedNames.length > 0) {
      const { data: nameRows } = await supabase
        .from('exercises')
        .select('id, name')
        .in('name', unresolvedNames)
        .is('deleted_at', null); // hide merge-soft-deleted duplicates
      nameResolvedIds = ((nameRows ?? []) as { id: string }[]).map((r) => r.id);
    }
    const directAnchors = await fetchDirectHistoryAnchors(supabase, user.id, [
      ...uuidIds,
      ...nameResolvedIds,
    ]);

    // USE PROGRAM_DATA: Create exercise blocks from pre-calculated program
    for (let exerciseIndex = 0; exerciseIndex < exercisesWithOverrides.length; exerciseIndex++) {
      const exercise = exercisesWithOverrides[exerciseIndex];
      const isCompound = exercise.primaryMuscle && ['chest', 'back', 'quads', 'hamstrings', 'glutes'].includes(exercise.primaryMuscle);
      const isFirstForMuscle = !seenMuscles.has(exercise.primaryMuscle);

      // Look up exercise_id from database by name (metadata feeds cold-start
      // transfer matching)
      const { data: dbExercise } = await supabase
        .from('exercises')
        .select('id, mechanic, default_rep_range, default_rir, primary_muscle, movement_pattern, equipment_required, min_weight_increment_kg, available_increments_kg, exercise_type, is_bodyweight')
        .eq('name', exercise.exerciseName)
        // Hide merge-soft-deleted duplicates: without this, a name shared with
        // a merged loser returns 2+ rows and .single() errors -> block skipped.
        .is('deleted_at', null)
        .single();

      // Use program_data's exerciseId ONLY if it's a real UUID — a placeholder
      // id fails the exercise_blocks.exercise_id UUID/FK constraint and
      // rejects the WHOLE insert (every block) -> an empty workout. Fall back
      // to the id we just looked up by name. Keep this in sync with
      // programSessionHasUsableExercises above, which display surfaces use to
      // predict whether this loop yields any blocks.
      const exerciseId = isUuid(exercise.exerciseId) ? exercise.exerciseId : dbExercise?.id;
      if (!exerciseId) continue; // Skip if exercise not found

      // Target weight, in priority order:
      //  1. DIRECT HISTORY (Fix 5): the user's own recency-decayed e1RM for
      //     THIS exercise, run through the SAME session-start recommender the
      //     live card uses (recommendSeedForSlot) — so the persisted target
      //     honors the ±10% recent-working-weight clamp, the all-sets bump
      //     gate (Fix 2), and the confirmed-regression step-down (Fix 4)
      //     instead of letting one strong set over-bump the stored plan. The
      //     weekly intensityModifier is NOT applied on this path — the RIR
      //     ramp already drives weekly intensification and multiplying by the
      //     scheduled modifier double-counts it (audit failure mode #1).
      //     Deload weeks are the exception: the modifier IS the deload's
      //     lightening mechanism, so it still applies there.
      //  2. TRUE COLD START: no direct history → the existing
      //     quickWeightEstimate transfer/profile ladder, unchanged.
      let targetWeight = 0;
      const dbExerciseType = (dbExercise as { exercise_type?: string | null } | null)?.exercise_type;
      const dbIsBodyweight = (dbExercise as { is_bodyweight?: boolean | null } | null)?.is_bodyweight;
      const isDurationExercise = dbExerciseType === 'duration_based';
      const direct = directAnchors.get(exerciseId);
      if (direct) {
        const seed = recommendSeedForSlot({
          role: 'working',
          targetRepRange: [exercise.repRange.min, exercise.repRange.max],
          targetRir: exercise.targetRir,
          minIncrementKg:
            (dbExercise as { min_weight_increment_kg?: number } | null)
              ?.min_weight_increment_kg || undefined,
          availableIncrementsKg:
            (dbExercise as { available_increments_kg?: number[] | null } | null)
              ?.available_increments_kg ?? undefined,
          anchorE1RMKg: direct.anchorE1RMKg,
          recentWorkingWeightKg: direct.recentWorkingWeightKg || undefined,
          prevSessionSets: direct.prevSessionSets,
          priorSessionSets: direct.priorSessionSets,
          exerciseType: isDurationExercise ? 'duration_based' : 'rep_based',
          isBodyweight: dbIsBodyweight ?? undefined,
        });
        if (seed.weightKg > 0) {
          // Duration seeds are last-session loads on a time-then-load ladder —
          // scaling them by the weekly intensity modifier has no meaning.
          targetWeight = progressionModifiers.isDeload && !isDurationExercise
            ? Math.round(seed.weightKg * progressionModifiers.intensityModifier * 2) / 2
            : seed.weightKg;
        }
      }
      if (isDurationExercise && targetWeight <= 0) {
        // LOUD skip: no cold-start load estimation for timed work — there is
        // no capacity curve for holds/carries. The block ships with the time
        // range and no fabricated load.
        console.warn(
          `[startMesocycleSession] ${exercise.exerciseName} is duration-based with no history — skipping cold-start load estimation.`
        );
      }
      if (!isDurationExercise && targetWeight <= 0 && userData?.height_cm && userData?.weight_kg) {
        const weightRec = quickWeightEstimate(
          exercise.exerciseName,
          exercise.repRange,
          exercise.targetRir,
          userData.weight_kg,
          userData.height_cm,
          userData.body_fat_percent || 20,
          userExperience,
          undefined,
          'kg',
          undefined,
          {
            transferCandidates,
            targetMeta: {
              primaryMuscle: dbExercise?.primary_muscle ?? exercise.primaryMuscle,
              movementPattern: dbExercise?.movement_pattern,
              equipmentRequired: dbExercise?.equipment_required,
            },
          }
        );
        const baseWeight = weightRec.recommendedWeight || 0;

        // Apply progressive overload: increase weight based on weekly intensity modifier
        // intensityModifier typically ranges from 1.0 (week 1) to 1.05-1.10 (later weeks)
        // Deload weeks have lower modifier (0.85-0.9)
        targetWeight = Math.round(baseWeight * progressionModifiers.intensityModifier * 2) / 2; // Round to nearest 0.5kg
      }

      // Generate warmup for first exercise of each muscle group
      let warmupSets: WarmupSet[] = [];
      if (isFirstForMuscle) {
        warmupSets = generateWarmupProtocol({
          workingWeight: targetWeight || 60,
          exercise: {
            id: exerciseId,
            name: exercise.exerciseName,
            primaryMuscle: exercise.primaryMuscle,
            secondaryMuscles: [],
            mechanic: isCompound ? 'compound' : 'isolation',
            defaultRepRange: [exercise.repRange.min, exercise.repRange.max] as [number, number],
            defaultRir: exercise.targetRir,
            minWeightIncrementKg: 2.5,
            formCues: [],
            commonMistakes: [],
            equipmentRequired: [],
            setupNote: '',
            movementPattern: isCompound ? 'compound' : 'isolation',
          },
          isFirstExercise: order === 1,
        });
        seenMuscles.add(exercise.primaryMuscle);
      }

      // Weekly auto-regulation delta for THIS exercise position in the week's plan
      const setAdjustment = weeklyAdjustmentPlan?.byExercise.get(
        exerciseKey(weekSessionIdx, exerciseIndex)
      );

      blocks.push({
        workout_session_id: sessionId,
        exercise_id: exerciseId,
        order: order++,
        // From program_data (respects session duration & fatigue budget),
        // plus the ±1 weekly adjustment from last week's muscle feedback.
        target_sets: setAdjustment ? setAdjustment.adjustedSets : exercise.sets,
        target_rep_range: [exercise.repRange.min, exercise.repRange.max],
        target_rir: exercise.targetRir,
        target_weight_kg: targetWeight, // From WeightEstimationEngine
        target_rest_seconds: exercise.restSeconds || getRestPeriod(isCompound, userGoal, exercise.primaryMuscle),
        suggestion_reason: `${programSession.dayName} - Week ${mesocycle.current_week}${progressionModifiers.isDeload ? ' (Deload)' : ''}${setAdjustment ? ` · ${setAdjustment.label}` : ''}`,
        warmup_protocol: { sets: warmupSets },
      });
    }
  }

  // Fallback: if program_data yielded no usable blocks — either there was no
  // program session (e.g. mesocycles created before program_data existed), or
  // it had exercises whose names didn't match the library so every lookup
  // above was skipped — build the session from today's target muscles. This
  // guarantees we never start an EMPTY workout when the day's muscles are
  // known. Matches primary_muscle case-insensitively so taxonomy casing
  // differences don't drop everything.
  if (blocks.length === 0 && todayWorkout?.muscles?.length) {
    // FALLBACK: Query exercises and use default logic (legacy behavior)
    const muscleList = todayWorkout.muscles.map((m) => m.toLowerCase());
    const { data: exercises } = await supabase
      .from('exercises')
      .select('*')
      .in('primary_muscle', muscleList)
      .is('deleted_at', null); // hide merge-soft-deleted duplicates

    if (exercises && exercises.length > 0) {
      type ExerciseRow = { id: string; name: string; primary_muscle: string; mechanic: string; default_rep_range: number[]; default_rir: number; movement_pattern?: string | null; equipment_required?: string[] | null };
      const exercisesByMuscle: Record<string, ExerciseRow[]> = {};
      (exercises as ExerciseRow[]).forEach((ex: ExerciseRow) => {
        if (!exercisesByMuscle[ex.primary_muscle]) {
          exercisesByMuscle[ex.primary_muscle] = [];
        }
        exercisesByMuscle[ex.primary_muscle].push(ex);
      });

      for (const muscle of todayWorkout.muscles) {
        const muscleExercises = exercisesByMuscle[muscle] || [];
        const selected = muscleExercises.slice(0, Math.min(2, muscleExercises.length));

        let isFirstExerciseForMuscle = !seenMuscles.has(muscle);

        for (const exercise of selected) {
          const isCompound = exercise.mechanic === 'compound';
          const fallbackIsDuration =
            (exercise as { exercise_type?: string | null }).exercise_type === 'duration_based';

          // Get weight estimate with progressive overload. Duration exercises
          // are skipped loudly: no capacity curve exists for timed work.
          let targetWeight = 0;
          if (fallbackIsDuration) {
            console.warn(
              `[startMesocycleSession] ${exercise.name} is duration-based — skipping cold-start load estimation.`
            );
          } else if (userData?.height_cm && userData?.weight_kg) {
            const repRange = exercise.default_rep_range || [8, 12];
            const weightRec = quickWeightEstimate(
              exercise.name,
              { min: repRange[0], max: repRange[1] },
              exercise.default_rir || 2,
              userData.weight_kg,
              userData.height_cm,
              userData.body_fat_percent || 20,
              userExperience,
              undefined,
              'kg',
              undefined,
              {
                transferCandidates,
                targetMeta: {
                  primaryMuscle: exercise.primary_muscle,
                  movementPattern: exercise.movement_pattern,
                  equipmentRequired: exercise.equipment_required,
                },
              }
            );
            const baseWeight = weightRec.recommendedWeight || 0;
            // Apply progressive overload intensity modifier
            targetWeight = Math.round(baseWeight * progressionModifiers.intensityModifier * 2) / 2;
          }

          let warmupSets: WarmupSet[] = [];
          if (isFirstExerciseForMuscle) {
            const repRange = (exercise.default_rep_range && exercise.default_rep_range.length >= 2
              ? [exercise.default_rep_range[0], exercise.default_rep_range[1]]
              : [8, 12]) as [number, number];

            warmupSets = generateWarmupProtocol({
              workingWeight: targetWeight || 60,
              exercise: {
                id: exercise.id,
                name: exercise.name,
                primaryMuscle: exercise.primary_muscle,
                secondaryMuscles: [],
                mechanic: isCompound ? 'compound' : 'isolation',
                defaultRepRange: repRange,
                defaultRir: exercise.default_rir || 2,
                minWeightIncrementKg: 2.5,
                formCues: [],
                commonMistakes: [],
                equipmentRequired: [],
                setupNote: '',
                movementPattern: isCompound ? 'compound' : 'isolation',
              },
              isFirstExercise: order === 1,
            });
            seenMuscles.add(muscle);
            isFirstExerciseForMuscle = false;
          }

          // Apply volume modifier for deload weeks (fallback uses 50% on deload)
          const baseSets = isCompound ? 4 : 3;
          const adjustedSets = progressionModifiers.isDeload
            ? Math.max(2, Math.round(baseSets * 0.5))
            : baseSets;

          blocks.push({
            workout_session_id: sessionId,
            exercise_id: exercise.id,
            order: order++,
            target_sets: adjustedSets,
            target_rep_range: exercise.default_rep_range || [8, 12],
            target_rir: exercise.default_rir || 2,
            target_weight_kg: targetWeight,
            target_rest_seconds: getRestPeriod(isCompound, userGoal, exercise.primary_muscle as MuscleGroup),
            suggestion_reason: `${todayWorkout.dayName} - Week ${mesocycle.current_week}${progressionModifiers.isDeload ? ' (Deload)' : ''}`,
            warmup_protocol: { sets: warmupSets },
          });
        }
      }
    }
  }

  if (blocks.length > 0) {
    const { error: blocksError } = await supabase.from('exercise_blocks').insert(blocks);
    if (blocksError) console.error('Failed to insert exercise blocks:', blocksError);
  }

  return { sessionId, resumedExisting: false };
}
