-- Higher training frequencies: 7-day weeks and two-a-day sessions
--
-- days_per_week counts planned SESSIONS per week (the convention interval
-- schedules established: the plan counts sessions, other columns drive the
-- calendar). Two-a-day training means up to 7 days x 2 = 14 sessions/week,
-- so the old <= 7 ceiling has to lift, and the calendar needs to know how
-- many of those sessions share a training day:
--
--   sessions_per_day = 1 -> one session per training date (unchanged default)
--   sessions_per_day = 2 -> each training date carries two consecutive slots
--                           of the split rotation (e.g. Push AM / Pull PM)
--
-- Existing rows keep the one-a-day behavior they already had.

ALTER TABLE mesocycles
  ADD COLUMN IF NOT EXISTS sessions_per_day INTEGER NOT NULL DEFAULT 1;

DO $$
BEGIN
  -- Lift the sessions-per-week ceiling from 7 to 14. The original constraint
  -- was an inline column CHECK, so its name is the autogenerated one.
  IF EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'mesocycles_days_per_week_check'
  ) THEN
    ALTER TABLE mesocycles DROP CONSTRAINT mesocycles_days_per_week_check;
  END IF;

  ALTER TABLE mesocycles
    ADD CONSTRAINT mesocycles_days_per_week_check
    CHECK (days_per_week >= 1 AND days_per_week <= 14);

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'mesocycles_sessions_per_day_check'
  ) THEN
    ALTER TABLE mesocycles
      ADD CONSTRAINT mesocycles_sessions_per_day_check
      CHECK (sessions_per_day BETWEEN 1 AND 2);
  END IF;

  -- More than 7 sessions/week is only expressible with two-a-day training;
  -- a once-a-day row claiming 8+ sessions could never be scheduled.
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'mesocycles_sessions_fit_week_check'
  ) THEN
    ALTER TABLE mesocycles
      ADD CONSTRAINT mesocycles_sessions_fit_week_check
      CHECK (days_per_week <= 7 * sessions_per_day);
  END IF;
END $$;

COMMENT ON COLUMN mesocycles.days_per_week IS
  'Planned SESSIONS per week (1-14). With sessions_per_day = 2 this counts both daily sessions (7 days x 2 = 14).';

COMMENT ON COLUMN mesocycles.sessions_per_day IS
  '1 = one session per training date; 2 = two-a-day (each training date carries two consecutive split-rotation slots).';
