-- Warmup engine backfill: canonical movement_pattern + rom_demands.
--
-- APPROVED by the user (2026-07-27) from the printed classification list
-- (docs/warmup-engine/CLASSIFICATION_REVIEW.md, generated by
-- scripts/printWarmupClassification.ts — regenerate with --sql to compare).
--
-- Review flags addressed before applying:
--   * Leg Extension was stored as 'knee_flexion' (a data error — extensions
--     classified as curls). Audit of every movement_pattern consumer found
--     the error had leaked beyond warmup: swap-similarity scoring gave leg
--     extensions a same-pattern bonus toward leg curls, and
--     getRelatedPatterns made hinges "related" to extensions. Fixed here
--     (-> isolation_knee_extension); comparison sites now canonicalize.
--   * Close Grip Bench Press / Dips (Tricep Focus) -> horizontal_press is
--     warmup-pattern only. NOTHING infers primary muscle from
--     movement_pattern (audited: muscle always comes from primary_muscle /
--     secondary_muscles); both stay triceps-primary, untouched here.
--
-- Custom exercises (is_custom rows) are NOT in this list — they can't be
-- enumerated at migration-authoring time. They keep their legacy tokens and
-- interoperate through services/warmupEngine.canonicalizePatternToken,
-- which every pattern comparison/lookup now routes through.
--
-- The derived legacy 'pattern' column (20241212000001) is deliberately NOT
-- rewritten: the in-code program/fatigue engines still key on the legacy
-- vocabulary, and all cross-column comparisons canonicalize. Retire it when
-- those tables are re-keyed canonically.

UPDATE exercises SET movement_pattern = 'isolation_elbow_flexion', rom_demands = ARRAY['deep_stretch'] WHERE name = '45° Preacher Curl';
UPDATE exercises SET movement_pattern = 'isolation_anti_extension', rom_demands = '{}'::TEXT[] WHERE name = 'Ab Wheel Rollout';
UPDATE exercises SET movement_pattern = 'lunge', rom_demands = '{}'::TEXT[] WHERE name = 'Adductor Side Lunge';
UPDATE exercises SET movement_pattern = 'horizontal_press', rom_demands = '{}'::TEXT[] WHERE name = 'Assisted Dip Machine';
UPDATE exercises SET movement_pattern = 'vertical_pull', rom_demands = ARRAY['overhead'] WHERE name = 'Assisted Pull-Up';
UPDATE exercises SET movement_pattern = 'vertical_pull', rom_demands = ARRAY['overhead'] WHERE name = 'Assisted Pull-Up Machine';
UPDATE exercises SET movement_pattern = 'hinge', rom_demands = '{}'::TEXT[] WHERE name = 'Back Extension';
UPDATE exercises SET movement_pattern = 'isolation_shoulder_horizontal_abduction', rom_demands = '{}'::TEXT[] WHERE name = 'Band Pull-Apart';
UPDATE exercises SET movement_pattern = 'isolation_hip_abduction', rom_demands = '{}'::TEXT[] WHERE name = 'Banded Lateral Walk';
UPDATE exercises SET movement_pattern = 'squat', rom_demands = ARRAY['deep_knee_flexion'] WHERE name = 'Barbell Back Squat';
UPDATE exercises SET movement_pattern = 'horizontal_press', rom_demands = '{}'::TEXT[] WHERE name = 'Barbell Bench Press';
UPDATE exercises SET movement_pattern = 'isolation_elbow_flexion', rom_demands = '{}'::TEXT[] WHERE name = 'Barbell Curl';
UPDATE exercises SET movement_pattern = 'isolation_wrist_extension', rom_demands = '{}'::TEXT[] WHERE name = 'Barbell Reverse Wrist Curl';
UPDATE exercises SET movement_pattern = 'horizontal_pull', rom_demands = '{}'::TEXT[] WHERE name = 'Barbell Row';
UPDATE exercises SET movement_pattern = 'isolation_scapular_elevation', rom_demands = '{}'::TEXT[] WHERE name = 'Barbell Shrug';
UPDATE exercises SET movement_pattern = 'isolation_wrist_flexion', rom_demands = '{}'::TEXT[] WHERE name = 'Barbell Wrist Curl';
UPDATE exercises SET movement_pattern = 'isolation_elbow_flexion', rom_demands = ARRAY['deep_stretch'] WHERE name = 'Bayesian Cable Curl';
UPDATE exercises SET movement_pattern = 'isolation_shoulder_abduction', rom_demands = ARRAY['behind_back'] WHERE name = 'Behind-the-Back Cable Lateral Raise';
UPDATE exercises SET movement_pattern = 'isolation_wrist_flexion', rom_demands = ARRAY['behind_back'] WHERE name = 'Behind-the-Back Wrist Curl';
UPDATE exercises SET movement_pattern = 'lunge', rom_demands = '{}'::TEXT[] WHERE name = 'Bulgarian Split Squat';
UPDATE exercises SET movement_pattern = 'isolation_elbow_flexion', rom_demands = '{}'::TEXT[] WHERE name = 'Cable Bicep Curl';
UPDATE exercises SET movement_pattern = 'isolation_shoulder_abduction', rom_demands = '{}'::TEXT[] WHERE name = 'Cable Cross Body Lateral Raise';
UPDATE exercises SET movement_pattern = 'isolation_spinal_flexion', rom_demands = ARRAY['spinal_flexion_loaded'] WHERE name = 'Cable Crunch';
UPDATE exercises SET movement_pattern = 'isolation_elbow_flexion', rom_demands = '{}'::TEXT[] WHERE name = 'Cable Curl';
UPDATE exercises SET movement_pattern = 'isolation_shoulder_horizontal_adduction', rom_demands = ARRAY['deep_stretch'] WHERE name = 'Cable Fly';
UPDATE exercises SET movement_pattern = 'isolation_hip_abduction', rom_demands = '{}'::TEXT[] WHERE name = 'Cable Hip Abduction';
UPDATE exercises SET movement_pattern = 'isolation_hip_adduction', rom_demands = '{}'::TEXT[] WHERE name = 'Cable Hip Adduction';
UPDATE exercises SET movement_pattern = 'isolation_elbow_extension', rom_demands = ARRAY['overhead', 'deep_stretch'] WHERE name = 'Cable Overhead Tricep Extension';
UPDATE exercises SET movement_pattern = 'hinge', rom_demands = '{}'::TEXT[] WHERE name = 'Cable Pull Through';
UPDATE exercises SET movement_pattern = 'horizontal_pull', rom_demands = '{}'::TEXT[] WHERE name = 'Cable Row';
UPDATE exercises SET movement_pattern = 'isolation_elbow_extension', rom_demands = '{}'::TEXT[] WHERE name = 'Cable Tricep Pushdown';
UPDATE exercises SET movement_pattern = 'vertical_pull', rom_demands = '{}'::TEXT[] WHERE name = 'Cable Upright Row';
UPDATE exercises SET movement_pattern = 'isolation_spinal_rotation', rom_demands = '{}'::TEXT[] WHERE name = 'Cable Woodchop';
UPDATE exercises SET movement_pattern = 'isolation_shoulder_abduction', rom_demands = '{}'::TEXT[] WHERE name = 'Cable Y-Raise';
UPDATE exercises SET movement_pattern = 'isolation_ankle_plantar', rom_demands = '{}'::TEXT[] WHERE name = 'Calf Press Machine';
UPDATE exercises SET movement_pattern = 'isolation_hip_flexion', rom_demands = '{}'::TEXT[] WHERE name = 'Captain''s Chair Leg Raise';
UPDATE exercises SET movement_pattern = 'horizontal_pull', rom_demands = '{}'::TEXT[] WHERE name = 'Chest Supported Row';
UPDATE exercises SET movement_pattern = 'isolation_hip_abduction', rom_demands = '{}'::TEXT[] WHERE name = 'Clamshell';
UPDATE exercises SET movement_pattern = 'horizontal_press', rom_demands = '{}'::TEXT[] WHERE name = 'Close Grip Bench Press';
UPDATE exercises SET movement_pattern = 'vertical_pull', rom_demands = ARRAY['overhead'] WHERE name = 'Close Grip Lat Pulldown';
UPDATE exercises SET movement_pattern = 'isolation_elbow_flexion', rom_demands = '{}'::TEXT[] WHERE name = 'Concentration Curl';
UPDATE exercises SET movement_pattern = 'isolation_anti_extension', rom_demands = '{}'::TEXT[] WHERE name = 'Copenhagen Plank';
UPDATE exercises SET movement_pattern = 'squat', rom_demands = ARRAY['deep_knee_flexion'] WHERE name = 'Cossack Squat';
UPDATE exercises SET movement_pattern = 'isolation_anti_extension', rom_demands = '{}'::TEXT[] WHERE name = 'Dead Bug';
UPDATE exercises SET movement_pattern = 'carry', rom_demands = ARRAY['overhead', 'deep_stretch'] WHERE name = 'Dead Hang';
UPDATE exercises SET movement_pattern = 'hinge', rom_demands = ARRAY['hip_hinge_deep'] WHERE name = 'Deadlift';
UPDATE exercises SET movement_pattern = 'horizontal_press', rom_demands = '{}'::TEXT[] WHERE name = 'Decline Barbell Press';
UPDATE exercises SET movement_pattern = 'isolation_spinal_flexion', rom_demands = '{}'::TEXT[] WHERE name = 'Decline Crunch';
UPDATE exercises SET movement_pattern = 'horizontal_press', rom_demands = '{}'::TEXT[] WHERE name = 'Dips (Chest Focus)';
UPDATE exercises SET movement_pattern = 'horizontal_press', rom_demands = '{}'::TEXT[] WHERE name = 'Dips (Tricep Focus)';
UPDATE exercises SET movement_pattern = 'isolation_ankle_plantar', rom_demands = '{}'::TEXT[] WHERE name = 'Donkey Calf Raise';
UPDATE exercises SET movement_pattern = 'horizontal_press', rom_demands = '{}'::TEXT[] WHERE name = 'Dumbbell Bench Press';
UPDATE exercises SET movement_pattern = 'isolation_elbow_flexion', rom_demands = '{}'::TEXT[] WHERE name = 'Dumbbell Curl';
UPDATE exercises SET movement_pattern = 'isolation_shoulder_horizontal_adduction', rom_demands = ARRAY['deep_stretch'] WHERE name = 'Dumbbell Fly';
UPDATE exercises SET movement_pattern = 'isolation_elbow_extension', rom_demands = '{}'::TEXT[] WHERE name = 'Dumbbell Kickback';
UPDATE exercises SET movement_pattern = 'horizontal_pull', rom_demands = '{}'::TEXT[] WHERE name = 'Dumbbell Row';
UPDATE exercises SET movement_pattern = 'vertical_press', rom_demands = ARRAY['overhead'] WHERE name = 'Dumbbell Shoulder Press';
UPDATE exercises SET movement_pattern = 'isolation_scapular_elevation', rom_demands = '{}'::TEXT[] WHERE name = 'Dumbbell Shrug';
UPDATE exercises SET movement_pattern = 'isolation_spinal_flexion', rom_demands = '{}'::TEXT[] WHERE name = 'Dumbbell Side Bend';
UPDATE exercises SET movement_pattern = 'isolation_wrist_flexion', rom_demands = '{}'::TEXT[] WHERE name = 'Dumbbell Wrist Curl';
UPDATE exercises SET movement_pattern = 'isolation_elbow_flexion', rom_demands = '{}'::TEXT[] WHERE name = 'EZ Bar Curl';
UPDATE exercises SET movement_pattern = 'isolation_elbow_flexion', rom_demands = '{}'::TEXT[] WHERE name = 'EZ Bar Reverse Curl';
UPDATE exercises SET movement_pattern = 'isolation_shoulder_horizontal_abduction', rom_demands = ARRAY['shoulder_external_rotation'] WHERE name = 'Face Pull';
UPDATE exercises SET movement_pattern = 'carry', rom_demands = '{}'::TEXT[] WHERE name = 'Farmer''s Carry';
UPDATE exercises SET movement_pattern = 'isolation_shoulder_flexion', rom_demands = '{}'::TEXT[] WHERE name = 'Front Raise';
UPDATE exercises SET movement_pattern = 'hinge', rom_demands = '{}'::TEXT[] WHERE name = 'Glute Bridge';
UPDATE exercises SET movement_pattern = 'hinge', rom_demands = '{}'::TEXT[] WHERE name = 'Glute Bridge Hold';
UPDATE exercises SET movement_pattern = 'hinge', rom_demands = '{}'::TEXT[] WHERE name = 'Glute Drive Machine';
UPDATE exercises SET movement_pattern = 'hinge', rom_demands = ARRAY['hip_hinge_deep', 'deep_stretch'] WHERE name = 'Good Morning';
UPDATE exercises SET movement_pattern = 'squat', rom_demands = ARRAY['deep_knee_flexion'] WHERE name = 'Hack Squat';
UPDATE exercises SET movement_pattern = 'isolation_elbow_flexion', rom_demands = '{}'::TEXT[] WHERE name = 'Hammer Curl';
UPDATE exercises SET movement_pattern = 'isolation_spinal_flexion', rom_demands = '{}'::TEXT[] WHERE name = 'Hammer Strength Ab Crunch';
UPDATE exercises SET movement_pattern = 'isolation_hip_flexion', rom_demands = '{}'::TEXT[] WHERE name = 'Hanging Leg Raise';
UPDATE exercises SET movement_pattern = 'isolation_hip_abduction', rom_demands = '{}'::TEXT[] WHERE name = 'Hip Abduction Machine';
UPDATE exercises SET movement_pattern = 'isolation_hip_adduction', rom_demands = '{}'::TEXT[] WHERE name = 'Hip Adduction Machine';
UPDATE exercises SET movement_pattern = 'hinge', rom_demands = '{}'::TEXT[] WHERE name = 'Hip Thrust';
UPDATE exercises SET movement_pattern = 'isolation_anti_extension', rom_demands = '{}'::TEXT[] WHERE name = 'Hollow Body Hold';
UPDATE exercises SET movement_pattern = 'isolation_elbow_flexion', rom_demands = ARRAY['deep_stretch'] WHERE name = 'Incline Dumbbell Curl';
UPDATE exercises SET movement_pattern = 'horizontal_press', rom_demands = '{}'::TEXT[] WHERE name = 'Incline Dumbbell Press';
UPDATE exercises SET movement_pattern = 'squat', rom_demands = ARRAY['deep_knee_flexion'] WHERE name = 'Incline Leg Press';
UPDATE exercises SET movement_pattern = 'hinge', rom_demands = ARRAY['spinal_flexion_loaded', 'deep_stretch'] WHERE name = 'Jefferson Curl';
UPDATE exercises SET movement_pattern = 'isolation_elbow_extension', rom_demands = '{}'::TEXT[] WHERE name = 'Katana Tricep Extension';
UPDATE exercises SET movement_pattern = 'isolation_hip_flexion', rom_demands = '{}'::TEXT[] WHERE name = 'L-Sit';
UPDATE exercises SET movement_pattern = 'vertical_pull', rom_demands = ARRAY['overhead'] WHERE name = 'Lat Pulldown';
UPDATE exercises SET movement_pattern = 'isolation_shoulder_abduction', rom_demands = '{}'::TEXT[] WHERE name = 'Lateral Raise';
UPDATE exercises SET movement_pattern = 'isolation_knee_extension', rom_demands = '{}'::TEXT[] WHERE name = 'Leg Extension';
UPDATE exercises SET movement_pattern = 'squat', rom_demands = ARRAY['deep_knee_flexion'] WHERE name = 'Leg Press';
UPDATE exercises SET movement_pattern = 'isolation_ankle_plantar', rom_demands = '{}'::TEXT[] WHERE name = 'Leg Press Calf Raise';
UPDATE exercises SET movement_pattern = 'isolation_knee_flexion', rom_demands = '{}'::TEXT[] WHERE name = 'Lying Leg Curl';
UPDATE exercises SET movement_pattern = 'isolation_spinal_flexion', rom_demands = '{}'::TEXT[] WHERE name = 'Machine Ab Crunch';
UPDATE exercises SET movement_pattern = 'isolation_spinal_extension', rom_demands = '{}'::TEXT[] WHERE name = 'Machine Back Extension';
UPDATE exercises SET movement_pattern = 'isolation_elbow_flexion', rom_demands = '{}'::TEXT[] WHERE name = 'Machine Bicep Curl';
UPDATE exercises SET movement_pattern = 'horizontal_press', rom_demands = '{}'::TEXT[] WHERE name = 'Machine Chest Press';
UPDATE exercises SET movement_pattern = 'isolation_shoulder_abduction', rom_demands = '{}'::TEXT[] WHERE name = 'Machine Lateral Raise';
UPDATE exercises SET movement_pattern = 'isolation_elbow_extension', rom_demands = '{}'::TEXT[] WHERE name = 'Machine Tricep Extension';
UPDATE exercises SET movement_pattern = 'horizontal_pull', rom_demands = '{}'::TEXT[] WHERE name = 'Meadows Row';
UPDATE exercises SET movement_pattern = 'isolation_knee_flexion', rom_demands = '{}'::TEXT[] WHERE name = 'Nordic Curl';
UPDATE exercises SET movement_pattern = 'carry', rom_demands = ARRAY['overhead', 'overhead_lockout'] WHERE name = 'Overhead Carry';
UPDATE exercises SET movement_pattern = 'vertical_press', rom_demands = ARRAY['overhead'] WHERE name = 'Overhead Press';
UPDATE exercises SET movement_pattern = 'isolation_elbow_extension', rom_demands = ARRAY['overhead', 'deep_stretch'] WHERE name = 'Overhead Tricep Extension';
UPDATE exercises SET movement_pattern = 'isolation_anti_rotation', rom_demands = '{}'::TEXT[] WHERE name = 'Pallof Press';
UPDATE exercises SET movement_pattern = 'isolation_shoulder_horizontal_adduction', rom_demands = ARRAY['deep_stretch'] WHERE name = 'Pec Deck';
UPDATE exercises SET movement_pattern = 'squat', rom_demands = ARRAY['deep_knee_flexion'] WHERE name = 'Pendulum Squat';
UPDATE exercises SET movement_pattern = 'isolation_anti_extension', rom_demands = '{}'::TEXT[] WHERE name = 'Plank';
UPDATE exercises SET movement_pattern = 'carry', rom_demands = '{}'::TEXT[] WHERE name = 'Plate Pinch Hold';
UPDATE exercises SET movement_pattern = 'isolation_elbow_flexion', rom_demands = ARRAY['deep_stretch'] WHERE name = 'Preacher Curl';
UPDATE exercises SET movement_pattern = 'isolation_shoulder_abduction', rom_demands = '{}'::TEXT[] WHERE name = 'Prone Y-Raise';
UPDATE exercises SET movement_pattern = 'vertical_pull', rom_demands = ARRAY['overhead'] WHERE name = 'Pull-Ups';
UPDATE exercises SET movement_pattern = 'isolation_anti_extension', rom_demands = '{}'::TEXT[] WHERE name = 'RKC Plank';
UPDATE exercises SET movement_pattern = 'isolation_shoulder_horizontal_abduction', rom_demands = ARRAY['deep_stretch'] WHERE name = 'Rear Delt Fly';
UPDATE exercises SET movement_pattern = 'isolation_shoulder_horizontal_abduction', rom_demands = '{}'::TEXT[] WHERE name = 'Rear Delt Machine';
UPDATE exercises SET movement_pattern = 'isolation_shoulder_horizontal_abduction', rom_demands = ARRAY['deep_stretch'] WHERE name = 'Reverse Cable Crossover';
UPDATE exercises SET movement_pattern = 'lunge', rom_demands = '{}'::TEXT[] WHERE name = 'Reverse Lunge';
UPDATE exercises SET movement_pattern = 'isolation_wrist_extension', rom_demands = '{}'::TEXT[] WHERE name = 'Reverse Wrist Curl';
UPDATE exercises SET movement_pattern = 'hinge', rom_demands = ARRAY['hip_hinge_deep', 'deep_stretch'] WHERE name = 'Romanian Deadlift';
UPDATE exercises SET movement_pattern = 'isolation_elbow_extension', rom_demands = '{}'::TEXT[] WHERE name = 'Rope Tricep Pushdown';
UPDATE exercises SET movement_pattern = 'isolation_spinal_rotation', rom_demands = '{}'::TEXT[] WHERE name = 'Russian Twist';
UPDATE exercises SET movement_pattern = 'horizontal_pull', rom_demands = '{}'::TEXT[] WHERE name = 'Seal Row';
UPDATE exercises SET movement_pattern = 'isolation_shoulder_horizontal_adduction', rom_demands = ARRAY['deep_stretch'] WHERE name = 'Seated Cable Fly';
UPDATE exercises SET movement_pattern = 'isolation_ankle_plantar', rom_demands = '{}'::TEXT[] WHERE name = 'Seated Calf Raise';
UPDATE exercises SET movement_pattern = 'isolation_knee_flexion', rom_demands = '{}'::TEXT[] WHERE name = 'Seated Leg Curl';
UPDATE exercises SET movement_pattern = 'horizontal_pull', rom_demands = '{}'::TEXT[] WHERE name = 'Seated Machine Row';
UPDATE exercises SET movement_pattern = 'isolation_anti_extension', rom_demands = '{}'::TEXT[] WHERE name = 'Side Plank';
UPDATE exercises SET movement_pattern = 'isolation_hip_abduction', rom_demands = '{}'::TEXT[] WHERE name = 'Side-Lying Hip Abduction';
UPDATE exercises SET movement_pattern = 'isolation_ankle_plantar', rom_demands = '{}'::TEXT[] WHERE name = 'Single Leg Calf Raise';
UPDATE exercises SET movement_pattern = 'hinge', rom_demands = '{}'::TEXT[] WHERE name = 'Single Leg Hip Thrust';
UPDATE exercises SET movement_pattern = 'hinge', rom_demands = ARRAY['hip_hinge_deep', 'deep_stretch'] WHERE name = 'Single Leg RDL';
UPDATE exercises SET movement_pattern = 'isolation_knee_extension', rom_demands = ARRAY['deep_knee_flexion', 'deep_stretch'] WHERE name = 'Sissy Squat';
UPDATE exercises SET movement_pattern = 'isolation_elbow_extension', rom_demands = '{}'::TEXT[] WHERE name = 'Skull Crusher';
UPDATE exercises SET movement_pattern = 'horizontal_press', rom_demands = '{}'::TEXT[] WHERE name = 'Smith Machine Bench Press';
UPDATE exercises SET movement_pattern = 'isolation_ankle_plantar', rom_demands = '{}'::TEXT[] WHERE name = 'Smith Machine Calf Raise';
UPDATE exercises SET movement_pattern = 'horizontal_press', rom_demands = '{}'::TEXT[] WHERE name = 'Smith Machine Incline Press';
UPDATE exercises SET movement_pattern = 'vertical_press', rom_demands = ARRAY['overhead'] WHERE name = 'Smith Machine Shoulder Press';
UPDATE exercises SET movement_pattern = 'squat', rom_demands = ARRAY['deep_knee_flexion'] WHERE name = 'Smith Machine Squat';
UPDATE exercises SET movement_pattern = 'isolation_ankle_plantar', rom_demands = '{}'::TEXT[] WHERE name = 'Standing Calf Raise';
UPDATE exercises SET movement_pattern = 'lunge', rom_demands = '{}'::TEXT[] WHERE name = 'Step Up';
UPDATE exercises SET movement_pattern = 'hinge', rom_demands = ARRAY['hip_hinge_deep', 'deep_stretch'] WHERE name = 'Stiff Leg Deadlift';
UPDATE exercises SET movement_pattern = 'isolation_shoulder_extension', rom_demands = ARRAY['overhead'] WHERE name = 'Straight Arm Pulldown';
UPDATE exercises SET movement_pattern = 'carry', rom_demands = '{}'::TEXT[] WHERE name = 'Suitcase Carry';
UPDATE exercises SET movement_pattern = 'hinge', rom_demands = ARRAY['hip_hinge_deep'] WHERE name = 'Sumo Deadlift';
UPDATE exercises SET movement_pattern = 'isolation_spinal_extension', rom_demands = '{}'::TEXT[] WHERE name = 'Superman Hold';
UPDATE exercises SET movement_pattern = 'isolation_elbow_extension', rom_demands = '{}'::TEXT[] WHERE name = 'Tricep Pushdown';
UPDATE exercises SET movement_pattern = 'isolation_elbow_extension', rom_demands = '{}'::TEXT[] WHERE name = 'Triceps Extension (Dumbbell)';
UPDATE exercises SET movement_pattern = 'vertical_pull', rom_demands = '{}'::TEXT[] WHERE name = 'Upright Row';
UPDATE exercises SET movement_pattern = 'lunge', rom_demands = '{}'::TEXT[] WHERE name = 'Walking Lunges';
UPDATE exercises SET movement_pattern = 'squat', rom_demands = ARRAY['deep_knee_flexion'] WHERE name = 'Wall Sit';
UPDATE exercises SET movement_pattern = 'horizontal_pull', rom_demands = '{}'::TEXT[] WHERE name = 'Wide-Grip Seated Cable Row';
UPDATE exercises SET movement_pattern = 'isolation_wrist_flexion', rom_demands = '{}'::TEXT[] WHERE name = 'Wrist Roller';
